passagemath/passagemath

src/doc/en/prep/Calculus.rst
src/sage/calculus/calculus.py
src/sage/calculus/functional.py
src/sage/functions/exp_integral.py
src/sage/functions/generalized.py
src/sage/functions/other.py
src/sage/functions/piecewise.py
src/sage/interfaces/giac.py
src/sage/interfaces/interface.py
src/sage/matrix/matrix1.pyx
src/sage/modules/free_module_element.pyx
src/sage/rings/polynomial/multi_polynomial.pyx
src/sage/rings/polynomial/multi_polynomial_ideal.py
src/sage/rings/polynomial/polynomial_element.pyx
src/sage/symbolic/expression.pyx
src/sage/symbolic/integration/integral.py
src/sage/symbolic/relation.py

By @orlitzky
Same as https://github.com/sagemath/sage/pull/38770

Add "needs" tags for giac and libgiac by @orlitzky

---

src/sage/features/__init__.py
src/sage/features/join_feature.py
src/sage/features/mip_backends.py
src/sage/features/sagemath.py
src/sage/features/sphinx.py

Split out from sagemath/sage#35095.

`sage.features` updates

---

.github/workflows/dist.yml

.github/workflows/dist.yml (wheels): Do not set LD_LIBRARY_PATH

---

README.md

README.md: Add upstream links and short descriptions

---

build/pkgs/sagemath_groups/dependencies
build/pkgs/sagemath_schemes/dependencies
pkgs/sagemath-eclib/setup.py
pkgs/sagemath-groups/MANIFEST.in
pkgs/sagemath-groups/pyproject.toml.m4
pkgs/sagemath-lcalc/pyproject.toml.m4
pkgs/sagemath-ntl/pyproject.toml.m4
pkgs/sagemath-polyhedra/MANIFEST.in
pkgs/sagemath-schemes/pyproject.toml.m4
pkgs/sagemath-singular/pyproject.toml.m4
src/sage/geometry/all__sagemath_groups.py
src/sage/geometry/palp_normal_form.pyx

Fix sagemath-{lcalc,ntl,polyhedra,schemes}

---

.github/workflows/dist.yml

dist.yml (wheels): Install libpng from spkg

---

.github/workflows/dist.yml

dist.yml (wheels) [macOS]: Use ldclassic

---

pkgs/sagemath-graphs/known-test-failures--modules--pari.json
pkgs/sagemath-graphs/known-test-failures--modules.json
pkgs/sagemath-graphs/known-test-failures.json
src/sage/graphs/base/boost_graph.pyx
src/sage/graphs/cographs.py
src/sage/graphs/connectivity.pyx
src/sage/graphs/generic_graph.py
src/sage/graphs/graph.py

These fixes may also be mergeable in upstream Sage. @dcoudert

Modularization fixes in `sage.graphs`

---

README.md

README.md: Update instructions

---

src/sage/modular/arithgroup/arithgroup_element.pyx
src/sage/modular/arithgroup/congroup.pyx

sage.modular.arithgroup: Fix for modularization workaround

---

build/pkgs/sagemath_categories/dependencies_check
build/pkgs/sagemath_combinat/dependencies_check
build/pkgs/sagemath_giac/dependencies_check
build/pkgs/sagemath_graphs/dependencies_check
build/pkgs/sagemath_polyhedra/dependencies_check
build/pkgs/sagemath_schemes/dependencies_check

- **build/pkgs/sagemath_giac/dependencies_check: Fix up**
- **build/pkgs/sagemath_graphs/dependencies_check: Update**
- **build/pkgs/sagemath_combinat/dependencies_check: Update**
- **build/pkgs/sagemath_polyhedra/dependencies_check: Update**
- **build/pkgs/sagemath_schemes/dependencies_check: Update**

Update dependencies_check for some modularized distributions

---

src/sage/databases/sql_db.py
src/sage/graphs/strongly_regular_db.pyx

- **src/sage/databases/sql_db.py: Add # needs**
- **src/sage/graphs/strongly_regular_db.pyx: Add # needs**

`sage.databases.sql_db`: Modularization fixes

---

pkgs/sagemath-flint/known-test-failures.json
src/sage/libs/ntl/ntl_GF2X.pyx

- **src/sage/libs/ntl/ntl_GF2X.pyx: Modularization fix (import)**
- **./sage --fixdoctests --distribution 'sagemath-flint' --update-known-test-failures**

sage.libs.ntl: Modularization fixes

---

build/pkgs/cutgeneratingfunctionology/SPKG.rst
build/pkgs/cutgeneratingfunctionology/dependencies
build/pkgs/cutgeneratingfunctionology/requirements.txt
build/pkgs/sage_numerical_interactive_mip/SPKG.rst
build/pkgs/sage_numerical_interactive_mip/dependencies
build/pkgs/sage_numerical_interactive_mip/requirements.txt

Same as https://github.com/sagemath/sage/pull/35122

Add sage-numerical-interactive-mip, cutgeneratingfunctionology as pip packages

---

pkgs/sagemath-combinat/known-test-failures--graphs.json
pkgs/sagemath-combinat/known-test-failures.json
src/sage/libs/symmetrica/__init__.py
src/sage/libs/symmetrica/sc.pxi
src/sage/libs/symmetrica/symmetrica.pxi

- **sage.libs.symmetrica: Modularization fixes (imports)**
- **./sage --fixdoctests --distribution 'sagemath-combinat' --update-known-test-failures**
- **./sage --fixdoctests --distribution 'sagemath-combinat[graphs]' --update-known-test-failures**

sage.libs.symmetrica modularization

---

pkgs/sagemath-symbolics/known-test-failures.json
src/sage/env.py
src/sage/features/databases.py
src/sage/geometry/hyperbolic_space/hyperbolic_geodesic.py
src/sage/groups/matrix_gps/matrix_group.py
src/sage/interfaces/magma.py
src/sage/manifolds/differentiable/integrated_curve.py
src/sage/matrix/matrix2.pyx
src/sage/matrix/matrix_double_dense.pyx
src/sage/misc/session.pyx
src/sage/quivers/ar_quiver.py
src/sage/rings/valuation/valuation.py

- **Add # needs in various places**

Add # needs in various places

---

src/sage/dynamics/complex_dynamics/mandel_julia.py

- **src/sage/dynamics/complex_dynamics/mandel_julia.py: Modularization fixes (imports)**

sage.dynamics.complex_dynamics: Modularization fixes (imports)

---

pkgs/sagemath-giac/README.rst

- https://pypi.org/project/passagemath-giac/
Here we add:
- Examples that illustrate how to get started and the scope of the distribution
- ...?
Help and suggestions welcome @parisseb @frederichan-IMJPRG

passagemath-giac README

---

pkgs/sagemath-categories/MANIFEST.in
pkgs/sagemath-combinat/MANIFEST.in
src/sage/knots/free_knotinfo_monoid.py
src/sage/monoids/indexed_free_monoid.py

- **pkgs/sagemath-categories: Move sage.monoids.indexed_free_monoid here from -combinat**
- **src/sage/knots/free_knotinfo_monoid.py: Add # needs**
- **src/sage/monoids/indexed_free_monoid.py: Add # needs**

sagemath-categories: Add sage.monoids.indexed_free_monoid

---

src/sage/graphs/bipartite_graph.py
src/sage/graphs/domination.py
src/sage/graphs/generators/smallgraphs.py
src/sage/graphs/generic_graph.py
src/sage/graphs/graph_database.py
src/sage/graphs/graph_list.py
src/sage/graphs/isgci.py
src/sage/graphs/matching.py

- **sage.graphs: Add # needs**
- **src/sage/graphs/bipartite_graph.py: Add # needs**
- **src/sage/graphs/domination.py: Add # needs**
- **src/sage/graphs/generic_graph.py: Add # needs**
- **src/sage/graphs/graph_database.py: Add # needs**
- **src/sage/graphs/graph_list.py: Add # needs**
- **src/sage/graphs/isgci.py: Add # needs**

sage.graphs modularization 3

---

.github/workflows/dist.yml

`dist.yml`: Upload to PyPI only after building wheels

---

.github/workflows/dist.yml
build/make/Makefile.in
pkgs/sagemath-polyhedra/pyproject.toml.m4

- **.github/workflows/dist.yml, build/make/Makefile.in: Add sagemath_nauty, sagemath_palp**
- **pkgs/sagemath-polyhedra/pyproject.toml.m4: Add extra 'palp'**

sagemath nauty 2

---

src/sage/misc/dev_tools.py
src/sage/misc/sageinspect.py

- **src/sage/misc/dev_tools.py: Update doctests**
- **src/sage/misc/sageinspect.py: Use import in a doctest**

sage.misc.dev tools modularization

---

.github/workflows/dist.yml
pkgs/sagemath-categories/known-test-failures.json
pkgs/sagemath-cddlib/pyproject.toml.m4
pkgs/sagemath-nauty/pyproject.toml.m4
pkgs/sagemath-palp/pyproject.toml.m4

- **pkgs/sagemath-{cddlib,nauty,palp}: Fix deps**

pkgs/sagemath-{cddlib,nauty,palp}: Fix deps

---

.github/workflows/dist.yml

- **.github/workflows/dist.yml (wheels) [macOS]: Use -headerpad_max_install_names**

dist.yml (wheels) [macOS]: Use -headerpad_max_install_names

---

.github/workflows/dist.yml
pkgs/sagemath-qepcad/README.rst
pkgs/sagemath-qepcad/repair_wheel.py
src/sage/interfaces/qepcad.py

- **pkgs/sagemath-qepcad/repair_wheel.py: Ship more**
- **pkgs/sagemath-qepcad/README.rst: Add example**
- **.github/workflows/dist.yml (wheels): Update CIBW_REPAIR_WHEEL_COMMAND_LINUX**
- **src/sage/interfaces/qepcad.py: Remove use of SAGE_LOCAL**

sagemath qepcad 3

---

README.md
pkgs/sagemath-graphs/README.rst

- https://pypi.org/project/passagemath-graphs/
Here we add:
- Examples that illustrate how to get started and the scope of the distributions
- ...?
Help and suggestions welcome @dcoudert @janmenjayap @szhorvat @soehms

passagemath-graphs README

---

build/pkgs/sagemath_doc_html/dependencies
build/pkgs/sagemath_gfan/type
build/pkgs/sagemath_nauty/type
build/pkgs/sagemath_palp/type

- **build/pkgs/sagemath_doc_html/dependencies: Add optional packages that appear in doc**
- **build/pkgs/sagemath_{gfan,nauty,palp}/type: standard**

doc dependencies

---

pkgs/sagemath-bliss/pyproject.toml.m4
pkgs/sagemath-brial/pyproject.toml.m4
pkgs/sagemath-categories/pyproject.toml.m4
pkgs/sagemath-cddlib/pyproject.toml.m4
pkgs/sagemath-combinat/pyproject.toml.m4
pkgs/sagemath-coxeter3/pyproject.toml.m4
pkgs/sagemath-flint/pyproject.toml.m4
pkgs/sagemath-frobby/pyproject.toml.m4
pkgs/sagemath-gap/pyproject.toml.m4
pkgs/sagemath-gfan/pyproject.toml.m4
pkgs/sagemath-giac/pyproject.toml.m4
pkgs/sagemath-glpk/pyproject.toml.m4
pkgs/sagemath-graphs/pyproject.toml.m4
pkgs/sagemath-groups/pyproject.toml.m4
pkgs/sagemath-latte-4ti2/pyproject.toml.m4
pkgs/sagemath-macaulay2/pyproject.toml.m4
pkgs/sagemath-modules/pyproject.toml.m4
pkgs/sagemath-msolve/pyproject.toml.m4
pkgs/sagemath-nauty/pyproject.toml.m4
pkgs/sagemath-palp/pyproject.toml.m4
pkgs/sagemath-pari/pyproject.toml.m4
pkgs/sagemath-plot/pyproject.toml.m4
pkgs/sagemath-polyhedra/pyproject.toml.m4
pkgs/sagemath-qepcad/pyproject.toml.m4
pkgs/sagemath-schemes/pyproject.toml.m4
pkgs/sagemath-symbolics/pyproject.toml.m4
pkgs/sagemath-topcom/pyproject.toml.m4

- **sed -E -i.bak '/project.optional-dependencies/,$s/SPKG_INSTALL_REQUIRES_sagemath_([a-z0-9_]*)/"passagemath-\1",/' pkgs/*/pyproject.toml.m4**
- **sed -E -i.bak 's/,[]]/]/' pkgs/*/pyproject.toml.m4**
- **pkgs/sagemath-polyhedra/pyproject.toml.m4: Fix up**

unpin optional dependencies

---

build/make/Makefile.in
pkgs/sagemath-singular/pyproject.toml.m4
pkgs/sagemath-singular/repair_wheel.py

- **pkgs/sagemath-singular/repair_wheel.py: New**
- **build/make/Makefile.in (*-cibuildwheel): Add dependencies, constraints on all noarch wheels**

sagemath singular repair wheel

---

build/pkgs/sagemath_doc_html/dependencies
build/pkgs/sagemath_doc_html/dependencies_optional
src/doc/en/reference/discrete_geometry/index.rst
src/doc/en/reference/interfaces/index.rst

- **src/doc/en/reference/interfaces/index.rst: Conditionalize on features**
- **build/pkgs/sagemath_doc_html/dependencies_optional: Move various dependencies here**
- **src/doc/en/reference/discrete_geometry/index.rst: Conditionalize on features**

doc conditionalize

---

build/pkgs/latte_int/SPKG.rst
pkgs/sagemath-latte-4ti2/README.rst
pkgs/sagemath-latte-4ti2/tox.ini
src/sage/all__sagemath_latte_4ti2.py

- **pkgs/sagemath-latte-4ti2/tox.ini: Update**
- **src/sage/all__sagemath_latte_4ti2.py: Import**
- **build/pkgs/latte_int/SPKG.rst: Add upstream links**
- **pkgs/sagemath-latte-4ti2/README.rst: Add details, examples**

passagemath-latte-4ti2 README

---

build/pkgs/nauty/SPKG.rst
pkgs/sagemath-nauty/README.rst
pkgs/sagemath-nauty/tox.ini
src/doc/en/reference/spkg/index.rst

Making the [passagemath-nauty](https://pypi.org/project/passagemath-nauty/) README more useful. @dcoudert 
- **build/pkgs/nauty/SPKG.rst: Update**
- **pkgs/sagemath-nauty/README.rst: Add link and examples**
- **pkgs/sagemath-nauty/tox.ini: Fix list of tested modules**
- **src/doc/en/reference/spkg/index.rst: Add nauty**
- **pkgs/sagemath-nauty/README.rst: Add links to documentation**

passagemath-nauty README

---

pkgs/sagemath-singular/README.rst
pkgs/sagemath-singular/pyproject.toml.m4
pkgs/sagemath-singular/repair_wheel.py
pkgs/sagemath-singular/tox.ini
src/sage/all__sagemath_singular.py

- **pkgs/sagemath-singular/README.rst: Update**
- **pkgs/sagemath-singular/pyproject.toml.m4: Define extra 'test'**
- **pkgs/sagemath-singular/tox.ini, src/sage/all__sagemath_singular.py: Set up for testing**
- **pkgs/sagemath-singular/pyproject.toml.m4: Fix repair_wheel path**
- **pkgs/sagemath-singular/repair_wheel.py: Fix up**

passagemath-singular: README, fixes

---

pkgs/sagemath-palp/README.rst
src/doc/en/reference/spkg/index.rst

- **pkgs/sagemath-palp/README.rst: Add details, examples**
- **src/doc/en/reference/spkg/index.rst: Add palp**

passagemath-palp: README

---

build/pkgs/topcom/SPKG.rst
build/pkgs/topcom/spkg-install.in
pkgs/sagemath-topcom/MANIFEST.in
pkgs/sagemath-topcom/README.rst
pkgs/sagemath-topcom/repair_wheel.py

- **build/pkgs/topcom/SPKG.rst: Add more specific URL**
- **build/pkgs/topcom/spkg-install.in: Use sdh_... functions**
- **pkgs/sagemath-topcom/MANIFEST.in: Remove bad item**
- **pkgs/sagemath-topcom/README.rst: Add description, example**
- **pkgs/sagemath-topcom/repair_wheel.py: Fix with list of topcom executables**

pkgs/sagemath-topcom: README, fixes

---

.github/workflows/dist.yml

- **.github/workflows/dist.yml: Run tox on the built wheels**
- **TMP: Build less**

dist.yml: Run tox on the built wheels

---

src/doc/en/thematic_tutorials/geometry/polyhedra_tutorial.rst
src/sage/algebras/free_algebra_quotient_element.py
src/sage/features/frobby.py
src/sage/rings/qqbar.py
src/sage/structure/coerce.pyx

- **src/doc/en/thematic_tutorials/geometry/polyhedra_tutorial.rst: Fix # needs**
- **src/sage/algebras/free_algebra_quotient_element.py: Use import in doctest**
- **src/sage/features/frobby.py: Fix doctest**
- **src/sage/rings/qqbar.py: Fix # needs**
- **src/sage/structure/coerce.pyx: Fix # needs**

Modularization fixes (doctests)

---

pkgs/sagemath-graphs/pyproject.toml.m4
pkgs/sagemath-rankwidth/pyproject.toml.m4
src/sage/graphs/graph.py

- **src/sage/graphs/graph.py: Use lazy_import for rankwidth**
- **pkgs/sagemath-graphs/pyproject.toml.m4: Declare extra 'rankwidth'**

Fix rankwidth imports, declare extra passagemath-graphs[rankwidth]

---

build/pkgs/sagemath_schemes/dependencies
pkgs/sagemath-eclib/README.rst
pkgs/sagemath-eclib/pyproject.toml.m4
pkgs/sagemath-eclib/tox.ini
pkgs/sagemath-schemes/MANIFEST.in
src/sage/all__sagemath_eclib.py
src/sage/all__sagemath_schemes.py
src/sage/databases/all.py
src/sage/databases/all__sagemath_schemes.py
src/sage/databases/cremona.py
src/sage/databases/db_modular_polynomials.py
src/sage/databases/stein_watkins.py

- **pkgs/sagemath-eclib: Fix testing**
- **pkgs/sagemath-eclib/README.rst: Expand**
- **pkgs/sagemath-schemes: Add some sage.databases**
- **src/sage/all__sagemath_eclib.py: Load all__sagemath_repl first**
- **build/pkgs/sagemath_schemes/dependencies: Add sagemath_singular**

pkgs/sagemath-eclib: README, fixes

---

build/pkgs/kerrgeodesic_gw/SPKG.rst
build/pkgs/kerrgeodesic_gw/dependencies
build/pkgs/kerrgeodesic_gw/dependencies_build
build/pkgs/kerrgeodesic_gw/requirements.txt
build/pkgs/kerrgeodesic_gw/type

- Part of https://github.com/sagemath/sage/issues/31164

build/pkgs/kerrgeodesic_gw: New pip package

---

pkgs/sagemath-modules/known-test-failures.json
pkgs/sagemath-plot/known-test-failures.json
src/sage/algebras/finite_gca.py
src/sage/combinat/integer_vector_weighted.py
src/sage/combinat/root_system/root_lattice_realizations.py
src/sage/doctest/control.py
src/sage/functions/hyperbolic.py
src/sage/functions/other.py
src/sage/geometry/toric_lattice_element.pyx
src/sage/groups/generic.py
src/sage/groups/matrix_gps/linear.py
src/sage/matrix/matrix_double_dense.pyx
src/sage/modules/free_quadratic_module_integer_symmetric.py
src/sage/modules/vector_double_dense.pyx
src/sage/quadratic_forms/binary_qf.py
src/sage/rings/complex_double.pyx
src/sage/rings/finite_rings/integer_mod_ring.py
src/sage/rings/invariants/invariant_theory.py
src/sage/rings/polynomial/laurent_polynomial_ring_base.py
src/sage/rings/polynomial/multi_polynomial_sequence.py
src/sage/structure/coerce.pyx

- **src/sage/algebras/finite_gca.py: Add # needs**
- **src/sage/combinat/integer_vector_weighted.py: Add # needs**
- **src/sage/combinat/root_system/root_lattice_realizations.py: Add # needs**
- **src/sage/functions: Add # needs**
- **src/sage/geometry: Add # needs**
- **src/sage/groups: Add # needs**
- **src/sage/{matrix,modules,quadratic_forms}: Add # needs**
- **src/sage/structure/coerce.pyx: Add # needs**
- **src/sage/doctest/control.py: Add more packages to list of features not to read from SPKG install record**
- **./sage --fixdoctests --distribution 'sagemath-plot' --update-known-test-failures**

Various # needs

---

pkgs/sagemath-planarity/README.rst

Expanding the README of https://pypi.org/project/passagemath-planarity/
Help and comments welcome @john-boyer-phd @dcoudert

pkgs/sagemath-planarity/README.rst: Add example

---

.github/workflows/dist.yml

`dist.yml`: Check the built wheels using tox, part 2

---

pkgs/sagemath-modules/known-test-failures.json
src/sage/features/ecm.py
src/sage/features/fricas.py
src/sage/features/frobby.py
src/sage/features/gfan.py
src/sage/features/giac.py
src/sage/features/msolve.py
src/sage/matroids/matroid.pyx

- **src/sage/features/fricas.py: Make 'fricas' a JoinFeature**
- **src/sage/features/ecm.py: Make 'ecm' a JoinFeature**
- **src/sage/features/gfan.py: Make 'gfan' a JoinFeature**
- **src/sage/features/frobby.py: Make 'frobby' a JoinFeature**
- **src/sage/features/giac.py: Make 'giac' a JoinFeature**
- **src/sage/features/msolve.py: Make 'msolve' a JoinFeature**
- **src/sage/features/giac.py: Make 'giac' a JoinFeature (fixup)**
- **src/sage/features/ecm.py: Add # needs**
- **src/sage/features: Update spkg type='standard'**
- **src/sage/matroids/matroid.pyx: Add # needs**

Declare various spkg features as JoinFeature

---

pkgs/sagemath-modules/known-test-failures.json
src/sage/arith/misc.py
src/sage/categories/coxeter_groups.py
src/sage/categories/examples/finite_dimensional_lie_algebras_with_basis.py
src/sage/categories/filtered_algebras.py
src/sage/categories/filtered_algebras_with_basis.py
src/sage/categories/finite_dimensional_algebras_with_basis.py
src/sage/categories/finite_dimensional_lie_algebras_with_basis.py
src/sage/categories/lie_algebras.py
src/sage/categories/lie_algebras_with_basis.py
src/sage/modules/with_basis/indexed_element.pyx

- **src/sage/arith/misc.py: Add # needs**
- **src/sage/modules/with_basis/indexed_element.pyx: Add # needs**

pkgs/sagemath-modules: Modularization fixes (# needs)

---

pkgs/sagemath-categories/known-test-failures.json
pkgs/sagemath-repl/MANIFEST.in
src/sage/tests/all.py
src/sage/tests/all__sagemath_repl.py
src/sage/tests/cython.pyx
src/sage/tests/stl_vector.pyx

- **pkgs/sagemath-repl: Remove Cython tests**

pkgs/sagemath-repl: Exclude cython tests

---

src/sage/modular/modform_hecketriangle/hecke_triangle_group_element.py

(import from sage.geometry.hyperbolic_space)

sage.modular.modform_hecketriangle.hecke_triangle_group_element: Modularization fix

---

.github/workflows/ci-wheels.yml
pkgs/sagemath-combinat/tox.ini
pkgs/sagemath-graphs/tox.ini
pkgs/sagemath-polyhedra/tox.ini
pkgs/sagemath-schemes/tox.ini

- **.github/workflows/ci-wheels.yml: Use github.event.workflow_run.id**
- **.github/workflows/ci-wheels.yml: Run all tox environments**
- **.github/workflows/ci-wheels.yml: Run fixdoctests for all tox environments**
- **pkgs/sagemath-polyhedra/tox.ini: standard factor**
- **.github/workflows/ci-wheels.yml: Run all tox environments (fixup)**
- **pkgs/sagemath-{combinat,graphs,schemes}/tox.ini: Set extras from factors**
- **.github/workflows/ci-wheels.yml: Ignore errors in fixdoctest**

dist wheels run tox 8

---

pkgs/sagemath-polyhedra/known-test-failures.json
src/sage/algebras/orlik_solomon.py
src/sage/doctest/control.py
src/sage/features/qepcad.py
src/sage/functions/exp_integral.py
src/sage/functions/gamma.py
src/sage/geometry/cone_critical_angles.py
src/sage/geometry/polyhedron/base_ZZ.py
src/sage/matrix/matrix2.pyx

- **src/sage/algebras/orlik_solomon.py: Add # needs**
- **src/sage/features/qepcad.py: Make it a JoinFeature**
- **src/sage/doctest/control.py: Override more spkg features**
- **src/sage/geometry: Add # needs**
- **src/sage/functions: Add # needs**
- **src/sage/matrix/matrix2.pyx: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-polyhedra' --update-known-test-failures**
- **src/sage/features/qepcad.py: Fix up**

pkgs/sagemath-polyhedra: Modularization fixes (doctests)

---

.github/workflows/ci-linux.yml

- **.github/workflows/ci-linux.yml: Remove standard-sitepackages**
- **.github/workflows/ci-linux.yml: Remove maximal-pre, use standard as basis for optional/experimental**

ci-linux.yml: Remove standard-sitepackages, maximal

---

build/pkgs/boost_cropped/spkg-install.in

build/pkgs/boost_cropped/spkg-install.in: Build boost_regex

---

pkgs/sagemath-macaulay2/README.rst
src/sage/all__sagemath_macaulay2.py

- **pkgs/sagemath-macaulay2/README.rst: Add links, example**
- **src/sage/all__sagemath_macaulay2.py: Import**
- **pkgs/sagemath-macaulay2/README.rst: More examples**

pkgs/sagemath-macaulay2: Expand README

---

pkgs/sagemath-plantri/README.rst
pkgs/sagemath-plantri/pyproject.toml.m4

- **pkgs/sagemath-plantri/README.rst: Add example**
- **pkgs/sagemath-plantri/pyproject.toml.m4: Fix extra 'test'**

pkgs/sagemath-plantri: Expand README, fix extra 'test'

---

.github/workflows/dist.yml
pkgs/sagemath-benzene/README.rst
pkgs/sagemath-buckygen/README.rst
src/sage/features/graph_generators.py

- **src/sage/features/graph_generators.py: In is_functional methods, use absolute_filename**
- **pkgs/sagemath-buckygen/README.rst: Add examples**
- **pkgs/sagemath-benzene/README.rst: Add examples**
- **.github/workflows/dist.yml (wheels): Build benzene**

pkgs/sagemath-{buckygen,benzene}: Expand README, fixes

---

.github/workflows/ci-wheels.yml

- **.github/workflows/ci-wheels.yml: Use inputs.run-id**
- **.github/workflows/ci-wheels.yml: Run fixdoctests also for empty extra**

dist wheels run tox 10

---

pkgs/sagemath-polyhedra/known-test-failures--standard.json
pkgs/sagemath-polyhedra/known-test-failures.json
src/sage/algebras/orlik_solomon.py
src/sage/all__sagemath_polyhedra.py
src/sage/combinat/designs/orthogonal_arrays_build_recursive.py
src/sage/combinat/posets/lattices.py
src/sage/doctest/control.py
src/sage/features/mip_backends.py
src/sage/functions/gamma.py
src/sage/graphs/graph.py
src/sage/graphs/matching.py
src/sage/knots/link.py

- **src/sage/features/mip_backends.py: New feature 'cvxpy'**
- **src/sage/doctest/control.py: Override spkg feature cvxpy**
- **src/sage/algebras/orlik_solomon.py: Add # needs**
- **src/sage/functions/gamma.py: Add # needs**
- **src/sage/combinat: Add # needs**
- **src/sage/all__sagemath_polyhedra.py: Make sure that sage.combinat.all__sagemath_graphs.Posets wins over sage.categories.all.Posets**
- **src/sage/knots/link.py: Add # needs**
- **src/sage/graphs: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-polyhedra*' --update-known-test-failures**

pkgs/sagemath-polyhedra: Fixes

---

pkgs/sagemath-combinat/known-test-failures--graphs.json
pkgs/sagemath-combinat/known-test-failures--modules.json
pkgs/sagemath-combinat/known-test-failures.json
src/sage/combinat/crystals/kirillov_reshetikhin.py
src/sage/combinat/gelfand_tsetlin_patterns.py
src/sage/combinat/partition.py

- **sage.combinat.partition: Move partitions_in_box here**
- **./sage --fixdoctests --distribution 'sagemath-combinat*' --update-known-test-failures**

partitions_in_box modularization

---

.github/workflows/ci-linux.yml
.github/workflows/docker.yml
build/pkgs/python3/dependencies
configure.ac
src/doc/en/developer/coding_basics.rst
src/meson.build
src/sage/databases/sloane.py
src/sage/doctest/parsing.py
src/sage/features/dot2tex.py
src/sage/features/sloane_database.py
src/sage/graphs/graph_latex.py
src/sage/groups/perm_gps/cubegroup.py
src/sage/matroids/meson.build
src/sage/rings/meson.build
src/sage_docbuild/conf.py

- **Introduce negated optional tag**
- **Edit optional needs tags explanation**
- **Add features**
- **Fix modularization regression**
- **Delete a spurious empty line**
- **Python3 build does not find openssl without pkgconf**
- **Materialize literal-blocks list before modifying nodes**
- **Add a small improvement**
- **Do not upload logs artifact for the default job**
- **Updated SageMath version to 10.5.rc1**
- **Fix meson build by adding missing python files**
- **the patch breaks some macOS installations**
- **Updated SageMath version to 10.5.rc2**
- **PKG_CONFIG must be empty if not found**
- **Updated SageMath version to 10.5**

Merge upstream release 10.5

---

.github/workflows/ci-wheels.yml
build/pkgs/libbraiding/SPKG.rst
build/pkgs/libhomfly/SPKG.rst
build/pkgs/sagemath_meataxe/dependencies
build/pkgs/sagemath_sirocco/dependencies
build/pkgs/sagemath_sirocco/spkg-check
build/pkgs/sirocco/SPKG.rst
pkgs/sagemath-homfly/README.rst
pkgs/sagemath-homfly/pyproject.toml.m4
pkgs/sagemath-homfly/setup.py
pkgs/sagemath-homfly/tox.ini
pkgs/sagemath-libbraiding/README.rst
pkgs/sagemath-libbraiding/pyproject.toml.m4
pkgs/sagemath-libbraiding/setup.py
pkgs/sagemath-libbraiding/tox.ini
pkgs/sagemath-meataxe/pyproject.toml.m4
pkgs/sagemath-sirocco/README.rst
pkgs/sagemath-sirocco/pyproject.toml.m4
pkgs/sagemath-sirocco/setup.py
pkgs/sagemath-sirocco/tox.ini
src/sage/all__sagemath_homfly.py
src/sage/all__sagemath_libbraiding.py
src/sage/all__sagemath_schemes.py
src/sage/all__sagemath_sirocco.py
src/sage/groups/artin.py
src/sage/groups/braid.py
src/sage/knots/link.py
src/sage/schemes/curves/zariski_vankampen.py

These distributions are now available:
- https://pypi.org/project/passagemath-homfly/
- https://pypi.org/project/passagemath-libbraiding/
- https://pypi.org/project/passagemath-sirocco/
Here we add:
- Examples that illustrate how to get started and the scope of the distributions
- ...?
Help and suggestions welcome @miguelmarco

passagemath-{libbraiding,libhomfly,sirocco} READMEs, testing

---

.github/workflows/dist.yml

dist.yml: Build optional wheels unconditionally

---

pkgs/sagemath-symbolics/known-test-failures.json
src/sage/features/fricas.py
src/sage/manifolds/differentiable/integrated_curve.py
src/sage/matrix/matrix2.pyx
src/sage/matrix/matrix_symbolic_dense.pyx
src/sage/matrix/matrix_symbolic_sparse.pyx
src/sage/rings/padics/generic_nodes.py
src/sage/rings/padics/local_generic.py
src/sage/rings/polynomial/ore_function_field.py
src/sage/rings/real_arb.pyx
src/sage/symbolic/constants_c_impl.pxi
src/sage/symbolic/expression_conversion_algebraic.py
src/sage/symbolic/pynac_impl.pxi

- **src/sage/symbolic: Add # needs**
- **src/sage/manifolds/differentiable/integrated_curve.py: Add # needs**
- **src/sage/matrix: Add # needs**
- **src/sage/features/fricas.py: Fix doctest output**
- **src/sage/matrix/matrix2.pyx: Add # needs**

pkgs/sagemath-symbolics: Doctest fixes

---

build/pkgs/_prereq/distros/alpine.txt
build/pkgs/_prereq/distros/conda.txt
build/pkgs/_prereq/distros/debian.txt
build/pkgs/_prereq/distros/fedora.txt
build/pkgs/_prereq/distros/freebsd.txt
build/pkgs/_prereq/distros/gentoo.txt
build/pkgs/_prereq/distros/nix.txt
build/pkgs/_prereq/distros/opensuse.txt
build/pkgs/_prereq/distros/slackware.txt
build/pkgs/_prereq/distros/void.txt

build/pkgs/_prereq/distros: Add flex and bison

---

pkgs/sagemath-gfan/pyproject.toml.m4
pkgs/sagemath-gfan/repair_wheel.py
pkgs/sagemath-gfan/tox.ini
src/sage/all__sagemath_gfan.py
src/sage/interfaces/gfan.py
src/sage/rings/polynomial/groebner_fan.py

- **src/sage/interfaces/gfan.py: Do not use the symlinks 'gfan_COMMAND' etc.**
- **src/sage/rings/polynomial/groebner_fan.py: Add # needs**
- **pkgs/sagemath-gfan: Set up testing**
- **pkgs/sagemath-gfan/repair_wheel.py: Do not include the symlinks**

pkgs/sagemath-gfan: Do not ship/use the symlinked executables

---

pkgs/sagemath-planarity/setup.py
pkgs/sagemath-rankwidth/setup.py
src/sage/graphs/graph_generators.py

- **pkgs/sagemath-planarity: Include pyx in wheel for tests**
- **pkgs/sagemath-rankwidth: Include pyx in wheel for tests**
- **src/sage/graphs/graph_generators.py: Add # needs**

pkgs/sagemath-graphs: Fix tests

---

.github/workflows/dist.yml

dist.yml: Disable use of NTL in giac

---

src/sage/combinat/partition.py
src/sage/modules/with_basis/cell_module.py

- **src/sage/combinat/partition.py: Add # needs**
- **src/sage/modules/with_basis/cell_module.py: Add # needs**

pkgs/sagemath-modules: Doctest fixes

---

src/sage/matrix/matrix_cyclo_dense.pyx
src/sage/rings/convert/mpfi.pyx

- **src/sage/rings/convert/mpfi.pyx: Modularize pari import**
- **src/sage/matrix/matrix_cyclo_dense.pyx: Add # needs**

pkgs/sagemath-flint: Modularization fixes

---

build/pkgs/ore_algebra/requirements.txt

build/pkgs/ore_algebra/requirements.txt: Unpin

---

build/pkgs/onetbb/spkg-install.in

build/pkgs/onetbb/spkg-install.in: Use TBB_ENABLE_IPO=OFF

---

src/sage/graphs/comparability.pyx
src/sage/graphs/connectivity.pyx
src/sage/graphs/convexity_properties.pyx
src/sage/graphs/digraph_generators.py
src/sage/graphs/domination.py
src/sage/graphs/generators/families.py
src/sage/graphs/generic_graph.py
src/sage/graphs/generic_graph_pyx.pyx
src/sage/graphs/graph.py
src/sage/graphs/graph_decompositions/modular_decomposition.pyx
src/sage/graphs/hypergraph_generators.py
src/sage/graphs/strongly_regular_db.pyx
src/sage/sets/set_from_iterator.py

- **src/sage/sets/set_from_iterator.py: Add # needs**
- **src/sage/graphs/strongly_regular_db.pyx: Add # needs**
- **src/sage/graphs/hypergraph_generators.py: Add # needs**
- **src/sage/graphs/comparability.pyx: Add # needs**
- **src/sage/graphs/connectivity.pyx: Add # needs**
- **src/sage/graphs/convexity_properties.pyx: Add # needs**
- **src/sage/graphs/digraph_generators.py: Add # needs**
- **src/sage/graphs/generators/families.py: Add # needs**
- **src/sage/graphs/generic_graph.py: Add # needs**
- **src/sage/graphs/generic_graph_pyx.pyx: Add # needs**
- **src/sage/graphs/domination.py: Add # needs**
- **src/sage/graphs/graph.py: Add # needs**
- **src/sage/graphs/graph_decompositions/modular_decomposition.pyx: Use try..except for import**

sage.graphs: Modularization fixes

---

.github/workflows/dist.yml

dist.yml (wheels): Make sure python3 prereq xz is installed

---

pkgs/sagemath-pari/known-test-failures.json
pkgs/sagemath-pari/pyproject.toml.m4
pkgs/sagemath-pari/repair_wheel.py
src/sage/features/pari.py
src/sage/interfaces/gp.py
src/sage/rings/finite_rings/element_pari_ffelt.pyx
src/sage/rings/finite_rings/finite_field_constructor.py
src/sage/rings/finite_rings/finite_field_pari_ffelt.py

- **src/sage/features/pari.py: New**
- **pkgs/sagemath-pari: Ship the 'gp' binary in the wheel**

pkgs/sagemath-pari: Ship the gp executable, access via Feature in sage.interfaces.gp

---

pkgs/sagemath-groups/MANIFEST.in
pkgs/sagemath-modules/MANIFEST.in
pkgs/sagemath-symbolics/MANIFEST.in
src/sage/groups/misc_gps/all__sagemath_modules.py
src/sage/groups/misc_gps/argument_groups.py
src/sage/groups/misc_gps/imaginary_groups.py
src/sage/rings/all__sagemath_symbolics.py
src/sage/rings/asymptotic/all.py
src/sage/rings/asymptotic/asymptotic_expansion_generators.py
src/sage/rings/asymptotic/asymptotic_ring.py
src/sage/rings/asymptotic/asymptotics_multivariate_generating_functions.py
src/sage/rings/asymptotic/growth_group.py
src/sage/rings/asymptotic/growth_group_cartesian.py
src/sage/rings/asymptotic/misc.py
src/sage/rings/asymptotic/term_monoid.py
src/sage/symbolic/ring.pyx

- **pkgs/sagemath-modules: Move sage.groups.misc_gps.{argument,imaginary}_groups here from sagemath-groups**
- **pkgs/sagemath-symbolics: Add sage.rings.asymptotic**
- **src/sage/rings/asymptotic, src/sage/symbolic: Add # needs**

pkgs/sagemath-symbolic: Add sage.rings.asymptotic

---

pkgs/sagemath-singular/known-test-failures.json
src/sage/all__sagemath_singular.py
src/sage/arith/misc.py

- **src/sage/all__sagemath_singular.py: Make sure the right RR wins**
- **src/sage/arith/misc.py: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-singular' --update-known-test-failures**

pkgs/sagemath-singular: Fix tests

---

pkgs/sagemath-modules/MANIFEST.in
pkgs/sagemath-modules/known-test-failures.json
pkgs/sagemath-symbolics/MANIFEST.in
src/sage/groups/misc_gps/argument_groups.py
src/sage/groups/misc_gps/imaginary_groups.py
src/sage/misc/functional.py
src/sage/rings/asymptotic/misc.py
src/sage/rings/complex_mpfr.pyx

- **pkgs/sagemath-modules: Move sage.rings.asymptotic.misc here from sagemath-symbolics**
- **src/sage/groups/misc_gps/argument_groups.py: Modularize imports**
- **src/sage/rings/asymptotic/misc.py: Modularize imports**
- **src/sage/rings/complex_mpfr.pyx: Add # needs**
- **src/sage/rings/asymptotic/misc.py: Add # needs**
- **src/sage/misc/functional.py: Add # needs**
- **src/sage/groups/misc_gps/imaginary_groups.py: Add # needs**
- **src/sage/groups/misc_gps/argument_groups.py: Modularize imports**
- **src/sage/groups/misc_gps/argument_groups.py: Add # needs**

pkgs/sagemath-modules: Add sage.rings.asymptotic.misc

---

pkgs/sagemath-categories/setup.py
src/sage/data_structures/pairing_heap.h
src/sage/data_structures/pairing_heap.pxd
src/sage/data_structures/pairing_heap.pyx

- **pkgs/sagemath-categories: Add sage.data_structures.pairing_heap**
- **src/sage/data_structures/pairing_heap.pyx: Add # needs**

pkgs/sagemath-categories: Add sage.data_structures.pairing_heap, set std=c++11

---

build/pkgs/ccache/spkg-install.in

build/pkgs/ccache/spkg-install.in: Allow downloading dependencies

---

pkgs/sagemath-singular/MANIFEST.in
pkgs/sagemath-singular/known-test-failures.json
pkgs/sagemath-singular/setup.py
pkgs/sagemath-symbolics/MANIFEST.in
pkgs/sagemath-symbolics/known-test-failures.json
pkgs/sagemath-symbolics/pyproject.toml.m4
pkgs/sagemath-symbolics/setup.py
src/sage/dynamics/finite_dynamical_system_catalog.py
src/sage/features/sagemath.py
src/sage/symbolic/all__sagemath_singular.py
src/sage/symbolic/comparison_impl.pxi
src/sage/symbolic/constants_c_impl.pxi
src/sage/symbolic/expression.pxd
src/sage/symbolic/expression.pyx
src/sage/symbolic/getitem_impl.pxi
src/sage/symbolic/pynac.pxi
src/sage/symbolic/pynac_constant_impl.pxi
src/sage/symbolic/pynac_function_impl.pxi
src/sage/symbolic/pynac_impl.pxi
src/sage/symbolic/pynac_wrap.h
src/sage/symbolic/series_impl.pxi
src/sage/symbolic/substitution_map_impl.pxi

- **src/sage/symbolic: Update 'sage_setup: distribution'**
- **src/sage/features/sagemath.py: Update 'sage.symbolic'**
- **src/sage/dynamics/finite_dynamical_system_catalog.py: Add # needs**
- **pkgs/sagemath-singular: Move sage.symbolic.expression here from sagemath-symbolics**
- **./sage --fixdoctests --distribution 'sagemath-singular' --update-known-test-failures**

pkgs/sagemath-singular: Ship sage.symbolic.expression (pynac) here for now

---

pkgs/sagemath-modules/MANIFEST.in
src/sage/rings/function_field/drinfeld_modules/action.py
src/sage/rings/function_field/drinfeld_modules/all.py
src/sage/rings/function_field/drinfeld_modules/charzero_drinfeld_module.py
src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py
src/sage/rings/function_field/drinfeld_modules/finite_drinfeld_module.py
src/sage/rings/function_field/drinfeld_modules/homset.py
src/sage/rings/function_field/drinfeld_modules/morphism.py

- **pkgs/sagemath-modules: Add sage.rings.function_field.drinfeld_modules**
- **src/sage/rings/function_field/drinfeld_modules/drinfeld_module.py: Use lazy_import**

pkgs/sagemath-modules: Add sage.rings.function_field.drinfeld_modules

---

pkgs/sagemath-combinat/known-test-failures--graphs.json
pkgs/sagemath-combinat/known-test-failures--modules.json
pkgs/sagemath-combinat/known-test-failures.json
pkgs/sagemath-graphs/known-test-failures--modules.json
pkgs/sagemath-graphs/known-test-failures.json
pkgs/sagemath-modules/MANIFEST.in
pkgs/sagemath-modules/known-test-failures.json
src/sage/algebras/all__sagemath_combinat.py
src/sage/algebras/all__sagemath_modules.py
src/sage/algebras/steenrod/all.py
src/sage/algebras/steenrod/steenrod_algebra.py
src/sage/algebras/steenrod/steenrod_algebra_bases.py
src/sage/algebras/steenrod/steenrod_algebra_misc.py
src/sage/algebras/steenrod/steenrod_algebra_mult.py
src/sage/modules/fp_graded/all.py
src/sage/modules/fp_graded/element.py
src/sage/modules/fp_graded/free_element.py
src/sage/modules/fp_graded/free_homspace.py
src/sage/modules/fp_graded/free_module.py
src/sage/modules/fp_graded/free_morphism.py
src/sage/modules/fp_graded/homspace.py
src/sage/modules/fp_graded/module.py
src/sage/modules/fp_graded/morphism.py
src/sage/modules/fp_graded/steenrod/all.py
src/sage/modules/fp_graded/steenrod/homspace.py
src/sage/modules/fp_graded/steenrod/module.py
src/sage/modules/fp_graded/steenrod/morphism.py
src/sage/modules/fp_graded/steenrod/profile.py

- **pkgs/sagemath-modules: Add sage.algebras.steenrod, sage.modules.fp_graded**
- **src/sage/algebras/steenrod: Add # needs**
- **src/sage/modules/fp_graded: Add # needs**
- **src/sage/modules/fp_graded: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-combinat*' --update-known-test-failures**
- **./sage --fixdoctests --distribution 'sagemath-graphs*' --update-known-test-failures**

pkgs/sagemath-modules: Add sage.algebras.steenrod

---

pkgs/sagemath-modules/MANIFEST.in
src/sage/algebras/all.py
src/sage/algebras/all__sagemath_modules.py
src/sage/algebras/lie_algebras/abelian.py
src/sage/algebras/lie_algebras/affine_lie_algebra.py
src/sage/algebras/lie_algebras/all.py
src/sage/algebras/lie_algebras/bch.py
src/sage/algebras/lie_algebras/bgg_dual_module.py
src/sage/algebras/lie_algebras/bgg_resolution.py
src/sage/algebras/lie_algebras/center_uea.py
src/sage/algebras/lie_algebras/classical_lie_algebra.py
src/sage/algebras/lie_algebras/examples.py
src/sage/algebras/lie_algebras/free_lie_algebra.py
src/sage/algebras/lie_algebras/heisenberg.py
src/sage/algebras/lie_algebras/lie_algebra.py
src/sage/algebras/lie_algebras/morphism.py
src/sage/algebras/lie_algebras/nilpotent_lie_algebra.py
src/sage/algebras/lie_algebras/onsager.py
src/sage/algebras/lie_algebras/poincare_birkhoff_witt.py
src/sage/algebras/lie_algebras/quotient.py
src/sage/algebras/lie_algebras/rank_two_heisenberg_virasoro.py
src/sage/algebras/lie_algebras/representation.py
src/sage/algebras/lie_algebras/structure_coefficients.py
src/sage/algebras/lie_algebras/subalgebra.py
src/sage/algebras/lie_algebras/symplectic_derivation.py
src/sage/algebras/lie_algebras/verma_module.py
src/sage/algebras/lie_algebras/virasoro.py
src/sage/categories/simplicial_sets.py
src/sage/combinat/root_system/cartan_matrix.py
src/sage/combinat/root_system/integrable_representations.py

- **pkgs/sagemath-modules: Add sage.algebras.lie_algebras**
- **src/sage/algebras/lie_algebras: Add # needs**
- **src/sage/algebras/all__sagemath_modules.py: Import lie_algebras**
- **src/sage/combinat/root_system: Add # needs**
- **src/sage/categories/simplicial_sets.py: Add # needs**
- **src/sage/algebras/all.py: Remove import of lie_algebras here**

pkgs/sagemath-modules: Add sage.algebras.lie_algebras

---

pkgs/sagemath-combinat/MANIFEST.in
src/sage/dynamics/all.py
src/sage/dynamics/all__sagemath_combinat.py
src/sage/dynamics/cellular_automata/all.py
src/sage/dynamics/cellular_automata/catalog.py
src/sage/dynamics/cellular_automata/elementary.py
src/sage/dynamics/cellular_automata/glca.py
src/sage/dynamics/cellular_automata/solitons.py

- **pkgs/sagemath-combinat: Add sage.dynamics.cellular_automata**
- **src/sage/dynamics/cellular_automata/elementary.py: lazy_import**
- **src/sage/dynamics: Update .all***

pkgs/sagemath-combinat: Add sage.dynamics.cellular_automata

---

pkgs/sagemath-gap/repair_wheel.py
pkgs/sagemath-maxima/repair_wheel.py

pkgs/sagemath-gap/repair_wheel.py: Remove the sage-conf dependency from the wheel

---

pkgs/sagemath-categories/known-test-failures.json
pkgs/sagemath-objects/MANIFEST.in
src/sage/tests/all__sagemath_objects.py
src/sage/tests/cython.pyx
src/sage/tests/stl_vector.pyx

- **pkgs/sagemath-objects: Add pyx files from src/sage/tests**

pkgs/sagemath-objects: Add Cython files from sage.tests

---

pkgs/sagemath-gap/known-test-failures.json
src/sage/categories/additive_magmas.py
src/sage/categories/bimodules.py
src/sage/categories/category.py
src/sage/categories/finite_groups.py
src/sage/categories/groups.py
src/sage/categories/hopf_algebras_with_basis.py
src/sage/categories/magmas.py
src/sage/categories/monoids.py
src/sage/categories/principal_ideal_domains.py
src/sage/categories/semigroups.py
src/sage/categories/semisimple_algebras.py
src/sage/libs/gap/libgap.pyx

- **Bimodules.an_instance: Fall back to RDF when RR is not available**
- **src/sage/libs/gap/libgap.pyx: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-gap' --update-known-test-failures**

pkgs/sagemath-gap: Doctest fixes

---

src/sage/categories/kahler_algebras.py

Modularization fix for code added in https://github.com/sagemath/sage/pull/39168 @25shriya

src/sage/categories/kahler_algebras.py: Move import into method

---

src/sage/categories/graded_algebras_with_basis.py
src/sage/categories/kahler_algebras.py
src/sage/combinat/partition.py
src/sage/functions/special.py
src/sage/misc/latex_macros.py

- **src/sage/misc/latex_macros.py: Now also catch AttributeError**
- **src/sage/functions/special.py: Update # needs scipy**
- **src/sage/combinat/partition.py: Add # needs**
- **src/sage/categories/graded_algebras_with_basis.py: Add # needs**
- **src/sage/categories/graded_algebras_with_basis.py: Update # needs**
- **src/sage/categories/kahler_algebras.py: Add # sage_setup: distribution**

pkgs/sagemath-categories: Fix tests

---

src/sage/algebras/orlik_solomon.py
src/sage/categories/magmas.py
src/sage/categories/modules_with_basis.py
src/sage/categories/monoids.py
src/sage/combinat/permutation.py
src/sage/combinat/shifted_primed_tableau.py
src/sage/graphs/graph_plot.py
src/sage/groups/artin.py
src/sage/groups/cubic_braid.py
src/sage/groups/group.pyx
src/sage/modules/fp_graded/module.py
src/sage/modules/fp_graded/morphism.py
src/sage/modules/with_basis/subquotient.py
src/sage/monoids/indexed_free_monoid.py
src/sage/quivers/algebra_elements.pyx
src/sage/rings/padics/padic_generic.py

- **src/sage/algebras/orlik_solomon.py: Add # needs**
- **src/sage/combinat: Add # needs**
- **src/sage/graphs/graph_plot.py: Add # needs**
- **src/sage/groups: Add # needs**
- **src/sage/modules: Add # needs**
- **src/sage/monoids/indexed_free_monoid.py: Add # needs**
- **src/sage/quivers/algebra_elements.pyx: Add # needs**
- **src/sage/rings/padics/padic_generic.py: Add # needs**

pkgs/sagemath-polyhedra: Doctest fixes

---

src/doc/en/installation/launching.rst
src/sage/ext_data/notebook-ipython/kernel.json.in
src/sage/meson.build

Backport of:
- https://github.com/sagemath/sage/pull/39773

Meson jupyter kernel by @tobiasdiez, backported

---

build/pkgs/scipy/patches/21069.patch

- Add https://github.com/scipy/scipy/pull/21069 as a patch

build/pkgs/scipy: Fix build on macOS with clang 17

---

.github/workflows/build.yml
.github/workflows/ci-wheels.yml

This adds the missing automatic testing on GH Actions @xuluze

.github/workflows/{build,ci-wheels}.yml: Test passagemath-cmr

---

.github/workflows/macos.yml
tox.ini

- **.github/workflows/macos.yml: Remove defunct macos-12 runs**
- **.github/workflows/macos.yml: Run 13, 14, 15**
- **tox.ini: Update xcode factors**

ci macos update

---

pkgs/sagemath-symbolics/known-test-failures.json
src/sage/libs/pari/tests.py
src/sage/rings/number_field/number_field.py
src/sage/rings/number_field/order.py
src/sage/rings/padics/padic_generic_element.pyx
src/sage/schemes/generic/morphism.py
src/sage/stats/distributions/discrete_gaussian_lattice.py

sagemath symbolics  tests 3

---

.github/workflows/dist.yml

The 1st job times out after 6 hours for manylinux aarch64

`dist.yml` (wheels): Move `brial`, `giac` to 2nd job

---

build/pkgs/_prereq/distros/arch.txt

build/pkgs/_prereq/distros/arch.txt: Add flex

---

.devcontainer/portability-voidlinux-minimal/devcontainer.json
.devcontainer/portability-voidlinux-minimal/portability-Dockerfile
.devcontainer/portability-voidlinux-musl-minimal/devcontainer.json
.devcontainer/portability-voidlinux-musl-minimal/portability-Dockerfile
.devcontainer/portability-voidlinux-musl-standard/devcontainer.json
.devcontainer/portability-voidlinux-musl-standard/portability-Dockerfile
.devcontainer/portability-voidlinux-standard/devcontainer.json
.devcontainer/portability-voidlinux-standard/portability-Dockerfile
.github/workflows/docker.yml
src/doc/en/developer/portability_platform_table.rst
tox.ini

- **tox.ini: Add testing on voidlinux**
- **tox -e update_docker_platforms**

CI Linux: Add voidlinux

---

.devcontainer/portability-fedora-40-arm64v8-minimal/devcontainer.json
.devcontainer/portability-fedora-40-arm64v8-minimal/portability-Dockerfile
.devcontainer/portability-fedora-40-arm64v8-standard/devcontainer.json
.devcontainer/portability-fedora-40-arm64v8-standard/portability-Dockerfile
.devcontainer/portability-fedora-41-arm64v8-minimal/devcontainer.json
.devcontainer/portability-fedora-41-arm64v8-minimal/portability-Dockerfile
.devcontainer/portability-fedora-41-arm64v8-standard/devcontainer.json
.devcontainer/portability-fedora-41-arm64v8-standard/portability-Dockerfile
.devcontainer/portability-fedora-42-arm64v8-minimal/devcontainer.json
.devcontainer/portability-fedora-42-arm64v8-minimal/portability-Dockerfile
.devcontainer/portability-fedora-42-arm64v8-standard/devcontainer.json
.devcontainer/portability-fedora-42-arm64v8-standard/portability-Dockerfile
.devcontainer/portability-fedora-43-arm64v8-minimal/devcontainer.json
.devcontainer/portability-fedora-43-arm64v8-minimal/portability-Dockerfile
.devcontainer/portability-fedora-43-arm64v8-standard/devcontainer.json
.devcontainer/portability-fedora-43-arm64v8-standard/portability-Dockerfile
.devcontainer/portability-fedora-43-minimal/devcontainer.json
.devcontainer/portability-fedora-43-minimal/portability-Dockerfile
.devcontainer/portability-fedora-43-standard/devcontainer.json
.devcontainer/portability-fedora-43-standard/portability-Dockerfile
.github/workflows/docker.yml
src/doc/en/developer/portability_platform_table.rst
tox.ini

CI Linux: Add fedora-43, fedora-*-arm64v8

---

build/pkgs/_prereq/distros/alpine.txt

build/pkgs/_prereq/distros/alpine.txt: Add linux-headers

---

.github/workflows/release-assets-publish.yml

- **.github/workflows/release-assets-publish.yml: Use run-id**
- **.github/workflows/release-assets-publish.yml: Pass token to gh**
- **.github/workflows/release-assets-publish.yml: gh -R**
- **.github/workflows/release-assets-publish.yml: Fix up**
- **.github/workflows/release-assets-publish.yml: gh release upload --clobber**

release-assets-publish.yml: Fix up

---

build/pkgs/lidia/dependencies
build/pkgs/lidia/spkg-install.in

build/pkgs/lidia/spkg-install.in: Run autoreconf

---

.github/workflows/ci-wheels.yml
.github/workflows/dist.yml

ci-wheels.yml: Add input fields for selecting Python versions, distributions, OSs; allow testing of published wheels

---

src/sage/rings/finite_rings/integer_mod_ring.py
src/sage/rings/polynomial/polynomial_ring.py

Previous updates were made by @mwageringel @saliola

`src/sage/rings`: Update doctests for macaulay 1.24.11

---

.github/workflows/ci-wheels.yml

.github/workflows/ci-wheels.yml: Cache the passagemath-conf wheelhouse

---

src/bin/sage-fixdoctests

src/bin/sage-fixdoctests: If invoked from repository root, use that as SAGE_ROOT

---

build/pkgs/sagemath_ecl/dependencies
build/pkgs/sagemath_maxima/dependencies
pkgs/sagemath-ecl/pyproject.toml.m4

- **pkgs/sagemath-ecl: Add missing dependency on gsl**
- **build/pkgs/sagemath_maxima/dependencies: Add missing dependency**

pkgs/sagemath-ecl, build/pkgs/sagemath_maxima: Add dependencies

---

src/sage/features/msolve.py

Fix msolve Feature test when `msolve` is not in `PATH`

---

src/sage/interfaces/qepcad.py

src/sage/interfaces/qepcad.py: Remove distro doctest

---

build/pkgs/pillow/spkg-install.in

- Fixes https://github.com/passagemath/passagemath/issues/874
- Workaround for https://github.com/python-pillow/Pillow/issues/8968

build/pkgs/pillow: Disable avif

---

README.md
constraints_pkgs.txt
pkgs/sagemath-cmr/README.rst

... to make the instructions in README.md "Full Installation from Source as passagemath" work @xuluze

constraints_pkgs.txt: Update to use pkgs/sage-conf-pypi

---

README.md

README.md: When using build isolation, install jinja2

---

src/sage/modules/free_module.py
src/sage/rings/polynomial/multi_polynomial_ring.py

- Seen in the tests of https://github.com/Macaulay2/M2/pull/3827

Some more `# needs sage.libs.pari`

---

src/sage/rings/polynomial/multi_polynomial_ring.py

Seen in the tests of https://github.com/Macaulay2/M2/pull/3827

Some more # needs sage.libs.pari (follow-up)

---

build/pkgs/glucose/patches/2.patch

- Add https://github.com/audemard/glucose/pull/2 as a patch
- Fixes #918

build/pkgs/glucose: Fix build on Linux aarch64

---

build/pkgs/python3/spkg-build.in
build/pkgs/python3/spkg-configure.m4

build/pkgs/python3: Check for _posixsubprocess

---

build/pkgs/macaulay2/spkg-install.in

Possible fix for
- https://github.com/Macaulay2/M2/issues/3849

build/pkgs/macaulay2/spkg-install.in: Use BUILD_SHARED_LIBS=ON

---

build/pkgs/onetbb/spkg-install.in

- Workaround for https://github.com/uxlfoundation/oneTBB/issues/1740

build/pkgs/onetbb/spkg-install.in: Workaround for alpine, voidlinux-musl

---

pkgs/sagemath-benzene/repair_wheel.py
pkgs/sagemath-buckygen/repair_wheel.py
pkgs/sagemath-cddlib/repair_wheel.py
pkgs/sagemath-ecl/repair_wheel.py
pkgs/sagemath-eclib/repair_wheel.py
pkgs/sagemath-fricas/repair_wheel.py
pkgs/sagemath-frobby/repair_wheel.py
pkgs/sagemath-gap/repair_wheel.py
pkgs/sagemath-gfan/repair_wheel.py
pkgs/sagemath-giac/repair_wheel.py
pkgs/sagemath-glucose/repair_wheel.py
pkgs/sagemath-kenzo/repair_wheel.py
pkgs/sagemath-kissat/repair_wheel.py
pkgs/sagemath-latte-4ti2/repair_wheel.py
pkgs/sagemath-lrslib/repair_wheel.py
pkgs/sagemath-macaulay2/repair_wheel.py
pkgs/sagemath-maxima/repair_wheel.py
pkgs/sagemath-msolve/repair_wheel.py
pkgs/sagemath-nauty/repair_wheel.py
pkgs/sagemath-palp/repair_wheel.py
pkgs/sagemath-pari/repair_wheel.py
pkgs/sagemath-plantri/repair_wheel.py
pkgs/sagemath-qepcad/repair_wheel.py
pkgs/sagemath-rubiks/repair_wheel.py
pkgs/sagemath-schemes/repair_wheel.py
pkgs/sagemath-singular/repair_wheel.py
pkgs/sagemath-sympow/repair_wheel.py
pkgs/sagemath-topcom/repair_wheel.py

pkgs/*/repair*/wheel.py: Exit with error status on failure

---

build/pkgs/glucose/patches/0002-fix-FPU-control-preventing-compilation-on-ARM-CPUs.patch
build/pkgs/glucose/patches/0003-Only-use-fpu_control.h-with-__GLIBC__.patch

build/pkgs/glucose: Fix build with musl libc

---

pkgs/sagemath-benzene/repair_wheel.py
pkgs/sagemath-buckygen/repair_wheel.py
pkgs/sagemath-cddlib/repair_wheel.py
pkgs/sagemath-ecl/repair_wheel.py
pkgs/sagemath-eclib/repair_wheel.py
pkgs/sagemath-fricas/repair_wheel.py
pkgs/sagemath-frobby/repair_wheel.py
pkgs/sagemath-gap/repair_wheel.py
pkgs/sagemath-gfan/repair_wheel.py
pkgs/sagemath-giac/repair_wheel.py
pkgs/sagemath-glucose/repair_wheel.py
pkgs/sagemath-kenzo/repair_wheel.py
pkgs/sagemath-kissat/repair_wheel.py
pkgs/sagemath-latte-4ti2/repair_wheel.py
pkgs/sagemath-lrslib/repair_wheel.py
pkgs/sagemath-macaulay2/repair_wheel.py
pkgs/sagemath-maxima/repair_wheel.py
pkgs/sagemath-msolve/repair_wheel.py
pkgs/sagemath-nauty/repair_wheel.py
pkgs/sagemath-palp/repair_wheel.py
pkgs/sagemath-pari/repair_wheel.py
pkgs/sagemath-plantri/repair_wheel.py
pkgs/sagemath-qepcad/repair_wheel.py
pkgs/sagemath-rubiks/repair_wheel.py
pkgs/sagemath-schemes/repair_wheel.py
pkgs/sagemath-singular/repair_wheel.py
pkgs/sagemath-sympow/repair_wheel.py
pkgs/sagemath-topcom/repair_wheel.py

Fixes repair_wheel for passagemath-cddlib and others on musllinux

pkgs/*/repair_wheel.py: Use bash

---

.github/workflows/dist.yml

dist.yml (wheels) [MACOS]: Set DYLD_FALLBACK_LIBRARY_PATH for delocate

---

pkgs/sagemath-combinat/pyproject.toml.m4
pkgs/sagemath-graphs/pyproject.toml.m4
pkgs/sagemath-modules/pyproject.toml.m4

- Fixes https://github.com/passagemath/passagemath/issues/1005

passagemath-{combinat,graphs,modules}: Add runtime dependency passagemath-environment

---

src/sage/categories/additive_groups.py
src/sage/categories/additive_magmas.py
src/sage/categories/additive_monoids.py
src/sage/categories/additive_semigroups.py
src/sage/categories/category.py
src/sage/categories/category_with_axiom.py
src/sage/categories/commutative_additive_groups.py
src/sage/categories/commutative_additive_monoids.py
src/sage/categories/commutative_additive_semigroups.py
src/sage/categories/commutative_rings.py
src/sage/categories/magmas.py
src/sage/categories/rings.py
src/sage/categories/rngs.py
src/sage/categories/semirings.py
src/sage/rings/integer_ring.pyx
src/sage/rings/polynomial/multi_polynomial.pyx
src/sage/rings/polynomial/polynomial_element.pyx
src/sage/rings/polynomial/polynomial_ring.py
src/sage/rings/rational.pyx
src/sage/rings/rational_field.py

Rebase of:
- https://github.com/sagemath/sage/issues/34182

Define `_lean_init_` methods for some elements, parents, axioms, and categories

---

build/pkgs/gap_packages/patches/digraphs-planarity-4.x.patch
build/pkgs/planarity/spkg-configure.m4

Backport of:
- https://github.com/sagemath/sage/pull/40153

update planarity to 4.0.0.0 by @dimpase, backported (part 2)

---

build/pkgs/gap/patches/headerpad_max_install_names.patch

Backport of:
- https://github.com/sagemath/sage/pull/40116

try to fix GAP build on some arm64 macOS systems by @dimpase, backported

---

build/pkgs/cibuildwheel/dependencies

- **build/pkgs/cibuildwheel/dependencies: Add dependencies**
- **build/pkgs/cibuildwheel/dependencies: Add dependencies (fixup)**

build/pkgs/cibuildwheel: Add dependencies

---

Makefile
bootstrap

- Fixes https://github.com/sagemath/sage/issues/35268

`bootstrap -s`: Add missing files generated from `pkgs/*/*.m4`

---

.github/workflows/dist-wheels-windows.yml

- **.github/workflows/dist-wheels-windows.yml: Fix hashing**
- **.github/workflows/dist-wheels-windows.yml: Use restore-keys**
- **.github/workflows/dist-wheels-windows.yml: Fix hashing more**

dist-wheels-windows.yml: Fix hashing

---

.github/workflows/dist-wheels-windows.yml

- **.github/workflows/dist-wheels-windows.yml: Make 'configure' script newer than configure tarball metadata**
- **.github/workflows/dist-wheels-windows.yml: Use more specific cache key**

dist-wheels-windows.yml: Caching, timestamp fixes

---

build/bin/sage-dist-helpers
build/pkgs/gmp/spkg-install.in

- **build/bin/sage-dist-helpers (sdh_generate_windows_lib_files): Factor out from build/pkgs/gmp/spkg-install.in**
- **build/pkgs/gmp/spkg-install.in, build/bin/sage-dist-helpers (sdh_generate_windows_lib_files): Fix handling of DESTDIR**

build/bin/sage-dist-helpers (sdh_generate_windows_lib_files): New

---

src/sage/doctest/control.py
src/sage/doctest/forker.py
src/sage/doctest/reporting.py

`sage.doctest`: Import fixes for Windows

---

.github/workflows/ci-mingw.yml
.github/workflows/mingw.yml

Part of
- https://github.com/passagemath/passagemath/issues/1069

Add reusable CI for MinGW build

---

src/sage/matrix/matrix_cmr_sparse.pyx
src/sage/matrix/seymour_decomposition.pyx

fix the row and column indexing for is_conetwork_matrix and add doctests in passagemath_cmr

---

.ci/write-dockerfile.sh
.devcontainer/tox-docker-in-docker/devcontainer.json

.ci/write-dockerfile.sh [voidlinux]: Update xbps first

---

build/bin/sage-bootstrap-python

build/bin/sage-bootstrap-python: Check for FancyURLopener - removed in Python 3.14

---

.github/workflows/dist-wheels-windows.yml
.github/workflows/mingw.yml

- **.github/workflows/mingw.yml: Also test on windows-11-arm**
- **.github/workflows/dist-wheels-windows.yml: Build Windows ARM wheels**

Test on and build wheels for Windows ARM

---

src/sage/stats/distributions/dgs_bern.c
src/sage/stats/distributions/dgs_gauss_dp.c
src/sage/stats/distributions/dgs_misc.h
src/sage/stats/distributions/discrete_gaussian_integer.pyx

This is for 
- https://github.com/passagemath/passagemath/pull/1077#issuecomment-3016759970

Replace use of `drand48` and `random` in `src/sage/stats/distributions/dgs*`

---

build/pkgs/primecount/patches/enable-win32-dll.patch

- https://github.com/kimwalisch/primecount/issues/89#issuecomment-3035771411

build/pkgs/primecount: Add patch for Windows

---

build/pkgs/glpk/spkg-install.in

build/pkgs/glpk/spkg-install.in [mingw]: Use -no-undefined, run autoreconf

---

pkgs/sagemath-glpk/README.rst
pkgs/sagemath-modules/README.rst
src/doc/en/developer/packaging_sage_library.rst

- **pkgs/sagemath-*/README.rst: Some remaining sagemath-* -> passagemath-***
- **src/doc/en/developer/packaging_sage_library.rst: Use passagemath package names, various updates**

pkgs/sagemath-modules, src/doc/en/developer/packaging_sage_library.rst: Use passagemath package names

---

.github/workflows/ci-linux-incremental.yml
build/pkgs/ncurses/spkg-install.in

build/pkgs/ncurses: Work around build failure with GCC 15

---

build/pkgs/boost_cropped/spkg-install.in

build/pkgs/boost_cropped/spkg-install.in: Disable 'boost_locale'

---

build/pkgs/boost_cropped/spkg-install.in

build/pkgs/boost_cropped: Disable boost_context

---

src/sage/matrix/matrix2.pyx
src/sage/matrix/matrix_integer_sparse.pyx
src/sage/rings/finite_rings/finite_field_base.pyx
src/sage/rings/morphism.pyx
src/sage/rings/padics/padic_generic_element.pyx
src/sage/rings/padics/padic_template_element.pxi
src/sage/rings/polynomial/polynomial_element.pyx
src/sage/rings/tate_algebra.py
src/sage/schemes/projective/projective_space.py

- **src/sage/rings/morphism.pyx: Add # needs**
- **src/sage/rings/tate_algebra.py: Add # needs**
- **src/sage/matrix: Add # needs**
- **src/sage/schemes/projective/projective_space.py: Add # needs**

Various `# needs`

---

pkgs/sagemath-singular/repair_wheel.py

pkgs/sagemath-singular/repair_wheel.py: Ship singular.info

---

build/pkgs/m4ri/patches/b178ed36bdd841a76b6595edb77631886e099406.patch

Backport of
- https://github.com/sagemath/sage/pull/40338 by @vbraun

Fix 32-bit segfault in m4ri by @vbraun, backported

---

.github/workflows/ci-wheels.yml

.github/workflows/ci-wheels.yml: Update from main

---

build/pkgs/sagemath_objects/spkg-install.in

build/pkgs/sagemath_objects/spkg-install.in: Fix for archlinux

---

build/pkgs/gcc/patches/gcc-sanitizer-glibc-2.42.patch

[passagemath-10.5.x] build/pkgs/gcc: Fix build with glibc 2.42

---

build/pkgs/qepcad/spkg-install.in
build/pkgs/saclib/spkg-install.in
build/pkgs/saclib/spkg-legacy-uninstall

build/pkgs/saclib: Fix build with GCC 15

---

build/pkgs/flint/patches/2383.patch

- https://github.com/flintlib/flint/pull/2383

build/pkgs/flint: Fix build on mingw32-clang-aarch64 

---

src/sage/matrix/seymour_decomposition.pxd
src/sage/matrix/seymour_decomposition.pyx

We can revert the removal if we decide to work on it.

src/sage/matrix/seymour_decomposition.p*: Remove unfinished SymbolicNode code

---

pkgs/sagemath-libecm/README.rst
pkgs/sagemath-libecm/known-test-failures.json
pkgs/sagemath-libecm/pyproject.toml.m4
pkgs/sagemath-libecm/tox.ini
src/sage/all__sagemath_libecm.py
src/sage/features/ecm.py
src/sage/interfaces/ecm.py
src/sage/libs/libecm.pyx

- Fixes #1327
@zimmermann6 FYI

passagemath-libecm: Fix use of the executable shipped by the wheel, set up testing, expand README

---

build/pkgs/libsemigroups/patches/semigroups-clang17.patch

build/pkgs/libsemigroups: Fix up patch

---

pkgs/sagemath-schemes/pyproject.toml.m4
pkgs/sagemath-schemes/repair_wheel.py

pkgs/sagemath-schemes: Also ship share/ellcurves via repair_wheel.py

---

README.md

README.md (Full Installation from Source as passagemath): Use `--force-reinstall` and `pip cache remove`

---

configure.ac

Fixes the installation method using `SAGE_CONF_TARGETS="build"` @GMS103

Fix `configure --disable-sagelib`

---

pkgs/sagemath-categories/pyproject.toml.m4
pkgs/sagemath-gap/pyproject.toml.m4

Follow up after #1404, two packages that missed the boat
@GMS103

Fix installation with pip without --no-build-isolation (after #1395), part 2

---

build/pkgs/dependent_bterms/SPKG.rst
build/pkgs/dependent_bterms/dependencies
build/pkgs/dependent_bterms/dependencies_build
build/pkgs/dependent_bterms/requirements.txt
build/pkgs/dependent_bterms/type

Add dependent_bterms by @behackl

build/pkgs/dependent_bterms: New

---

build/bin/sage-print-system-package-command
build/bin/sage-spkg-info

- **build/bin/sage-spkg-info: Fix markup**
- **build/bin/sage-print-system-package-command: Fix up**

build/bin/sage-spkg-info: Fix up

---

bootstrap
build/sage_bootstrap/app.py
build/sage_bootstrap/package.py

- **sage --package properties: Print 'description' property**
- **bootstrap: Use 'description' package property**

sage --package properties: Print 'description' property

---

.ci/write-dockerfile.sh
build/make/Makefile.in
tox.ini

- Resolves https://github.com/sagemath/sage/issues/32785

build/make/Makefile.in: Update SAGE_CHECK defaults from CI scripts

---

.github/workflows/dist-wheels-windows.yml
build/pkgs/cibuildwheel/requirements.txt

https://cibuildwheel.pypa.io/en/stable/changelog/#v314

Update cibuildwheel to 3.1.4

---

src/bin/sage-fixdoctests

Fix `sage --fixdoctests --distribution sagemath-standard`

---

build/pkgs/fricas/patches/0001-Makefile.in-install-src-Change-installed-fricas-scri.patch
build/pkgs/fricas/patches/0002-Makefile.in-install-src-ecl-Set-ECLDIR.patch
pkgs/sagemath-ecl/pyproject.toml.m4
pkgs/sagemath-ecl/repair_wheel.py
pkgs/sagemath-environment/pyproject.toml.m4
pkgs/sagemath-fricas/README.rst
pkgs/sagemath-fricas/pyproject.toml.m4
pkgs/sagemath-fricas/repair_wheel.py
src/bin/sage

pkgs/sagemath-fricas: Relocation and dependency fixes

---

build/pkgs/fricas/patches/0002-Makefile.in-install-src-ecl-Set-ECLDIR.patch
pkgs/sagemath-fricas/README.rst
src/bin/sage
src/bin/sage-venv-config
src/sage/all__sagemath_fricas.py

ECLDIR fixes for passagemath-fricas

---

build/pkgs/zftools/SPKG.rst
build/pkgs/zftools/dependencies
build/pkgs/zftools/requirements.txt
build/pkgs/zftools/type

build/pkgs/zftools: New

---

src/sage/libs/symmetrica/symmetrica.pxi

Fix segfault in symmetrica doctest

---

build/pkgs/boolean_cayley_graphs/SPKG.rst
build/pkgs/boolean_cayley_graphs/dependencies
build/pkgs/boolean_cayley_graphs/requirements.txt
build/pkgs/boolean_cayley_graphs/type

build/pkgs/boolean_cayley_graphs: New

---

build/pkgs/hypigu/SPKG.rst
build/pkgs/hypigu/dependencies
build/pkgs/hypigu/requirements.txt
build/pkgs/hypigu/type

build/pkgs/hypigu: New

---

build/pkgs/abelfunctions/SPKG.rst
build/pkgs/abelfunctions/dependencies
build/pkgs/abelfunctions/dependencies_build
build/pkgs/abelfunctions/requirements.txt
build/pkgs/abelfunctions/type

build/pkgs/abelfunctions: New

---

build/pkgs/ecl/spkg-configure.m4

build/pkgs/ecl/spkg-configure.m4: Check whether ecl COMPILE-FILE works

---

build/pkgs/dd_functions/SPKG.rst
build/pkgs/dd_functions/dependencies
build/pkgs/dd_functions/requirements.txt
build/pkgs/dd_functions/type

build/pkgs/dd_functions: New

---

build/bin/sage-print-system-package-command
build/bin/sage-spkg-info

... and add commands for Sage distribution and pip there.

`sage -info`: Change 'Equivalent System Packages' to 'Installation Commands'

---

build/pkgs/circkit/SPKG.rst
build/pkgs/circkit/dependencies
build/pkgs/circkit/requirements.txt
build/pkgs/circkit/type

build/pkgs/circkit: New

---

build/pkgs/msinvar/SPKG.rst
build/pkgs/msinvar/dependencies
build/pkgs/msinvar/requirements.txt
build/pkgs/msinvar/type

build/pkgs/msinvar: New

---

build/pkgs/stdpairs/SPKG.rst
build/pkgs/stdpairs/dependencies
build/pkgs/stdpairs/requirements.txt
build/pkgs/stdpairs/type

build/pkgs/stdpairs: New

---

build/pkgs/stallings_graphs/SPKG.rst
build/pkgs/stallings_graphs/dependencies
build/pkgs/stallings_graphs/requirements.txt
build/pkgs/stallings_graphs/type

build/pkgs/stallings_graphs: New

---

.github/workflows/macos.yml

https://github.com/actions/runner-images?tab=readme-ov-file#available-images
https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md

.github/workflows/macos.yml: Test on macos-26

---

build/pkgs/schubertpy/SPKG.rst
build/pkgs/schubertpy/dependencies
build/pkgs/schubertpy/requirements.txt
build/pkgs/schubertpy/type

build/pkgs/schubertpy: New

---

src/sage/libs/all.py

Fixup after https://github.com/passagemath/passagemath/pull/1618

src/sage/libs/all.py: Remove import from sage.libs.all__sagemath_giac

---

.github/workflows/dist.yml

The SAGE_LOCAL cache was not created because the condition was always false

.github/workflows/dist.yml (wheels-optional): Fix SAGE_LOCAL caching
