passagemath/passagemath

src/bin/sage-update-version
Bare `sed -i` does not work on macOS, and the `i` command needs a backslash
=> `src/bin/sage-update-version`: fix non-portable uses of `sed`

build/pkgs/brial/type, build/pkgs/sagemath_brial/type
=> Make `brial`, `sagemath_brial` standard again for now

src/sage_setup/autogen/interpreters/specs/cdf.py
Split out from sagemath/sage#35095.
Fixes #42
=> `src/sage_setup/autogen/interpreters/specs/cdf.py`: Remove ancient workaround

src/sage/matroids/graphic_matroid.pxd, src/sage/matroids/graphic_matroid.pyx
Hopefully this does not cause a big performance regression.
- Fixes #43
=> `sage.matroids.graphic_matroid`: Do not cimport from sage.graphs

src/sage/libs/flint/flint_wrap.h
Cherry-picked from https://github.com/sagemath/sage/pull/38227
Fixes https://github.com/sagemath/sage/issues/38242
=> `src/sage/libs/flint/flint_wrap.h`: Work around 'I' symbol clash

bootstrap-conda, build/make/Makefile.in, build/sage_bootstrap/app.py, build/sage_bootstrap/cmdline.py, build/sage_bootstrap/creator.py, build/sage_bootstrap/package.py, m4/sage_spkg_collect.m4, tox.ini
Using new commands `sage --package dependencies` and `sage --package properties`, we eliminate direct references to `build/pkgs/` from various scripts and reduce code duplication in reading SPKG metadata.
In particular, we simplify the `configure`-time compilation of dependency information for `build/make/Makefile` in `m4/sage_spkg_collect.m4`; this also gives a bit of a speedup when running `./configure`. 
We complement the `build/make/Makefile` variables `deps_SPKG` by new variables `build_deps_SPKG` and `check_deps_SPKG`. This is refactoring only; there should be no change in behavior (also note that no `dependencies_build` file is added here.) Together with sagemath/sage#36738, this is also preparation for improving the parallelization of build phases of various packages. As it gives …
=> Refactor `bootstrap-conda`, `m4/sage_spkg_collect.m4` through sage-package; handle `dependencies_build`

README.md, configure.ac
Marking `--enable-editable` as experimental.
Currently the editable (monolithic) Sage library does not properly interop with modularized distributions such as **sagemath-brial**.
- https://github.com/sagemath/sage/pull/38439
=> configure.ac: Make --disable-editable the default

.github/workflows/dist.yml
=> `dist.yml` (wheels): Do not try to upload passagemath-giac wheel for now (too large)

build/make/install
Rarely helpful and too much noise.
=> build/make/install: Do not print ALL-ENVIRONMENT-VARIABLES

pkgs/sagemath-standard-no-symbolics/MANIFEST.in
This takes care of #102, but in follow-ups various modules should be sorted into proper distributions.
=> sagemath-standard-no-symbolics: Include everything not shipped by another distribution

.github/workflows/docker.yml
After the upgrade to upload-artifact v4, we see `Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`
https://github.com/passagemath/passagemath/actions/runs/11431706897/job/31801071603#step:13:29
The reason is that we run the default platform (ubuntu-jammy) twice in one workflow.
=> docker.yml: Disambiguate log artifact names

pkgs/sagemath-standard-no-symbolics/MANIFEST.in
=> sagemath-standard-no-symbolics: Do not prune what is still needed

src/sage/misc/sageinspect.py
=> `sage.misc.sageinspect`: Do not fail when `sage_getsource` returns `None`

src/sage_docbuild/conf.py
=> `sage_docbuild.conf` (`add_page_context`): Handle the case `__file__` = `None`

.github/workflows/dist.yml
=> dist.yml (wheels): On PRs, only build wheels for one Python version

pkgs/sagemath-eclib/pyproject.toml.m4, pkgs/sagemath-singular/pyproject.toml.m4
To fix:
```
from sage.rings.rational cimport Rational
from sage.structure.element cimport Element
from sage.rings.integer cimport Integer
from sage.rings.finite_rings.integer_mod cimport IntegerMod_abstract
from sage.rings.finite_rings.element_givaro cimport Cache_givaro
^
------------------------------------------------------------
sage/libs/singular/singular.pxd:9:0: 'sage/rings/finite_rings/element_givaro.pxd' not found
```
=> pkgs/sagemath-{singular,eclib}: Add dependencies

src/sage/numerical/interactive_simplex_method.py
We remove the ad-hoc conversion of data to `RDF` in `InteractiveLPProblem.feasible_set`.  This is outdated and problematic:
- the polyhedra code over `RDF` is not robust at all 
- Sage has good support for algebraic polyhedra, in particular via normaliz.
We also make the printing code in `_latex_product` more robust: 
- it no longer relies on `SR` to decide whether a coefficient needs to be wrapped in parens; instead, we use the same simple test that `sage.misc.repr.coeff_repr` already uses
- recognizing trivial coefficients (0, 1) is switched to comparing text instead of comparing elements - in order to support fields such as `SR` where `==` is magic
Rebased version of:
- sagemath/sage#31312
Author: @mkoeppe, @ComboProblem
Resolves sagemath/sage#31312.
Same as …
=> `sage.numerical.interactive_simplex_method`: improve support for base fields other than `QQ` and `RDF`

pkgs/sagemath-modules/known-test-failures.json, pkgs/sagemath-polyhedra/known-test-failures.json, src/sage/matroids/advanced.py, src/sage/matroids/circuit_closures_matroid.pyx, src/sage/matroids/circuits_matroid.pyx, src/sage/matroids/constructor.py, src/sage/matroids/database_collections.py, src/sage/matroids/database_matroids.py, src/sage/matroids/dual_matroid.py, src/sage/matroids/flats_matroid.pyx, src/sage/matroids/linear_matroid.pyx, src/sage/matroids/matroid.pyx, src/sage/matroids/unpickling.pyx
`sage.matroids` is shipped by the distribution **passagemath-modules**. 
- Adding `# needs` for use of graphs and other features in doctest examples
- Some `import` fixes
This should also be suitable for upstream SageMath @gmou3
=> `sage.matroids`: Modularization fixes

.github/workflows/dist.yml
The build (using QEMU) exceeds 6 hours, so we skip it for now
=> `dist.yml` (wheels): Remove linux-aarch64

build/pkgs/tox/spkg-configure.m4, build/pkgs/tox/version_requirements.txt
Needed for testing editable installations
=> build/pkgs/tox/install-requires.txt: >= 4.11

.ci/write-dockerfile.sh
The `.tox` subdirectories are never cleaned and take too much space in the images
=> .ci/write-dockerfile.sh: Do not run testsuites of the modularized distributions

pkgs/sagemath-categories/known-test-failures.json, pkgs/sagemath-repl/known-test-failures.json, src/sage/all.py, src/sage/misc/all.py, src/sage/misc/all__sagemath_repl.py, src/sage/misc/benchmark.py, src/sage/misc/sageinspect.py
- **src/sage/misc/all__sagemath_repl.py: Move import from sage.misc.sh here**
- **src/sage/misc/all__sagemath_repl.py: Move import from sage.misc.classgraph here**
- **src/sage/misc/benchmark.py: Add # needs**
- **src/sage/misc/sageinspect.py: Update self-referential doctest**
- **src/sage/misc/all__sagemath_repl.py: Move import from sage.misc.remote_file here; remove some duplicates in sage.misc.all**
- **./sage --fixdoctests --distribution 'sagemath-repl' --update-known-test-failures**
=> sagemath-repl fixes

pkgs/sagemath-graphs/known-test-failures--modules.json, pkgs/sagemath-graphs/known-test-failures.json, src/sage/combinat/designs/covering_array.py, src/sage/combinat/designs/designs_pyx.pyx, src/sage/graphs/connectivity.pyx, src/sage/graphs/domination.py, src/sage/graphs/generic_graph.py, src/sage/graphs/graph.py, src/sage/graphs/graph_decompositions/slice_decomposition.pyx, src/sage/graphs/matching.py, src/sage/graphs/spanning_tree.pyx, src/sage/graphs/strongly_regular_db.pyx, src/sage/sets/recursively_enumerated_set.pyx
- **src/sage/graphs/generic_graph.py (flow): Make numerical weights work without mpfr**
- **src/sage/graphs/graph.py: Add # needs**
- **src/sage/sets/recursively_enumerated_set.pyx: Add # needs**
- **src/sage/graphs/strongly_regular_db.pyx: Add # needs**
- **src/sage/graphs/spanning_tree.pyx: Add # needs**
- **src/sage/graphs/matching.py: Make numerical weights work without mpfr**
- **src/sage/graphs/matching.py: Add # needs**
- **src/sage/graphs/domination.py: Add # needs**
- **src/sage/graphs/connectivity.pyx: Add # needs**
- **src/sage/combinat/designs/covering_array.py: Add # needs**
- **src/sage/combinat/designs/designs_pyx.pyx: Add # needs**
- **src/sage/graphs/graph_decompositions/slice_decomposition.pyx: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-graphs' …
=> sage.graphs: Modularization fixes

pkgs/sagemath-modules/known-test-failures.json, src/sage/algebras/orlik_solomon.py, src/sage/groups/matrix_gps/matrix_group.py, src/sage/matrix/matrix2.pyx, src/sage/modules/with_basis/indexed_element.pyx, src/sage/modules/with_basis/invariant.py, src/sage/quadratic_forms/binary_qf.py, src/sage/quadratic_forms/bqf_class_group.py, src/sage/quadratic_forms/count_local_2.pyx, src/sage/tensor/modules/free_module_automorphism.py
- **sage.matrix, sage.modules: Add # needs**
- **src/sage/matrix/matrix2.pyx: Fall back to more generic computation when pari is not available**
- **src/sage/algebras/orlik_solomon.py: Add # needs**
- **src/sage/modules/with_basis/invariant.py: Move import into method**
- **src/sage/groups/matrix_gps: Add # needs**
- **src/sage/quadratic_forms: Add # needs**
- **src/sage/tensor/modules: Add # needs**
=> sage.modules modularization 2

src/sage/doctest/control.py, src/sage/features/cddlib.py
- **src/sage/doctest/control.py: Add giac to list of features not to read from SPKG install record**
- **src/sage/features/cddlib.py: Add cddexec_gmp to all_features**
=> Define feature `cddexec_gmp`, override SPKG feature `giac` by runtime feature

pkgs/sagemath-categories/MANIFEST.in, pkgs/sagemath-combinat/MANIFEST.in, pkgs/sagemath-modules/MANIFEST.in, src/sage/algebras/all__sagemath_combinat.py, src/sage/algebras/all__sagemath_modules.py, src/sage/algebras/commutative_dga.py, src/sage/algebras/finite_gca.py, src/sage/combinat/all__sagemath_categories.py, src/sage/combinat/all__sagemath_combinat.py, src/sage/combinat/integer_vector_weighted.py
- **pkgs/sagemath-categories: Move sage.combinat.integer_vector_weighted here from -combinat**
- **pkgs/sagemath-modules: Move sage.algebras.finite_gca here from -combinat**
- **src/sage/combinat/all__sagemath_categories.py: lazy_import WeightedIntegerVectors here**
- **src/sage/combinat/integer_vector_weighted.py: Add # needs**
- **pkgs/sagemath-modules: Move sage.algebras.commutative_dga here from -combinat**
- **src/sage/algebras/commutative_dga.py: Use lazy_import for FreeAlgebra**
- **src/sage/algebras/finite_gca.py: Add # needs**
=> sagemath-modules: Add sage.combinat.integer_vector_weighted, sage.algebras.{commutative_dga,finite_gca}

pkgs/sagemath-flint/README.rst
- https://pypi.org/project/passagemath-flint/
Here we add:
- Examples that illustrate how to get started and the scope of the distribution
...?
Help and suggestions welcome @fredrik-johansson @oscarbenjamin @mezzarobba
=> passagemath-flint README

pkgs/sagemath-categories/known-test-failures.json, pkgs/sagemath-repl/known-test-failures.json, src/sage/combinat/integer_vector_weighted.py, src/sage/doctest/check_tolerance.py, src/sage/doctest/forker.py, src/sage/doctest/parsing.py, src/sage/env.py, src/sage/misc/latex.py, src/sage/misc/latex_macros.py, src/sage/rings/power_series_ring_element.pyx
- **src/sage/combinat/integer_vector_weighted.py: Add # needs**
- **src/sage/doctest: Add # needs**
- **src/sage/env.py: Add # needs**
- **src/sage/misc/latex.py: Add # needs**
- **src/sage/misc/latex_macros.py: Adjust doctest**
- **src/sage/rings/power_series_ring_element.pyx: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-repl' --update-known-test-failures**
=> sagemath categories doctest fixes

pkgs/sagemath-gap/README.rst
- https://pypi.org/project/passagemath-gap/
Here we add:
- Examples that illustrate how to get started and the scope of the distribution
- ...?
Help and suggestions welcome @fingolfin @hulpke
=> passagemath-gap README

README.md, pkgs/sagemath-modules/README.rst
- https://pypi.org/project/passagemath-modules/
Here we add:
- Examples that illustrate how to get started and the scope of the distribution
...?
In particular this package includes `sage.matroids` @gmou3 @xuluze and `sage.tensor` @egourgoulhon 
Help and suggestions welcome
=> passagemath-modules README

pkgs/sagemath-symbolics/README.rst
This distribution is now available: [passagemath-symbolics](https://pypi.org/project/passagemath-symbolics/)
Here we expand the README to include more usage examples, including SageManifolds examples. Help and comments welcome @egourgoulhon
=> pkgs/sagemath-symbolics/README.rst: Add SageManifolds links, example

pkgs/sagemath-singular/README.rst
This distribution is now available: https://pypi.org/project/passagemath-singular/
Here we expand the README, adding a description, a link to the Singular homepage, and examples.
Help and suggestions welcome @hannes14 @wdecker @jankoboehm
=> pkgs/sagemath-singular/README.rst: Add description, link, examples

pkgs/sagemath-modules/known-test-failures.json, src/sage/arith/misc.py, src/sage/functions/gamma.py, src/sage/functions/special.py, src/sage/rings/complex_double.pyx, src/sage/rings/complex_mpc.pyx, src/sage/rings/finite_rings/integer_mod_ring.py, src/sage/rings/polynomial/laurent_polynomial_ring_base.py, src/sage/rings/real_mpfr.pyx, src/sage/structure/element.pyx
- **src/sage/rings/complex_mpc.pyx (late_import): Do not fail when sage.rings.qqbar cannot be imported**
- **src/sage/arith/misc.py: Add # needs**
- **src/sage/functions: Add # needs**
- **src/sage/structure/element.pyx: Add # needs**
=> Modularization fix for sage.rings.complex_mpc

pkgs/sagemath-combinat/known-test-failures--graphs.json, pkgs/sagemath-combinat/known-test-failures--modules.json, pkgs/sagemath-combinat/known-test-failures.json, pkgs/sagemath-combinat/pyproject.toml.m4, src/sage/algebras/hecke_algebras/ariki_koike_specht_modules.py, src/sage/algebras/quantum_oscillator.py, src/sage/categories/discrete_valuation.py, src/sage/categories/filtered_modules_with_basis.py, src/sage/categories/finite_complex_reflection_groups.py, src/sage/categories/finite_dimensional_lie_algebras_with_basis.py, src/sage/combinat/matrices/dancing_links.pyx, src/sage/combinat/partition.py, src/sage/combinat/permutation.py, src/sage/combinat/plane_partition.py, src/sage/combinat/q_analogues.py, src/sage/combinat/sf/sf.py, src/sage/data_structures/stream.py, src/sage/libs/lrcalc/lrcalc.py, src/sage/monoids/indexed_free_monoid.py, src/sage/rings/finite_rings/integer_mod_ring.py, src/sage/rings/lazy_series.py, src/sage/rings/lazy_series_ring.py, src/sage/rings/polynomial/multi_polynomial_ring.py, src/sage/rings/polynomial/polynomial_element.pyx, src/sage/structure/unique_representation.py
- **src/sage/data_structures/stream.py: Do not import SR, use isinstance(..., Expression) instead**
- **src/sage/data_structures/stream.py: Add # needs**
- **src/sage/combinat/sf/sf.py: Use lazy_import**
- **src/sage/algebras: Add # needs**
- **src/sage/combinat: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-combinat' --update-known-test-failures**
- **./sage --fixdoctests --distribution 'sagemath-combinat[graphs]' --update-known-test-failures**
- **./sage --fixdoctests --distribution 'sagemath-combinat[modules]' --update-known-test-failures**
- **pkgs/sagemath-combinat/pyproject.toml.m4: Define extra 'findstat'**
- **src/sage/libs/lrcalc/lrcalc.py: Add # needs**
- …
=> pkgs/sagemath-combinat: Modularization fixes (# needs)

pkgs/sagemath-eclib/README.rst, src/sage/all__sagemath_eclib.py
- **src/sage/all__sagemath_eclib.py: Import from sage.libs**
- **pkgs/sagemath-eclib/README.rst: Add link to sage.interfaces.mwrank documentation**
=> pkgs/sagemath-eclib: Fix toplevel

pkgs/sagemath-schemes/known-test-failures--ntl.json, pkgs/sagemath-schemes/known-test-failures--pari.json, pkgs/sagemath-schemes/known-test-failures.json, src/sage/categories/filtered_modules_with_basis.py, src/sage/coding/kasami_codes.pyx, src/sage/dynamics/arithmetic_dynamics/projective_ds.py, src/sage/geometry/cone_critical_angles.py, src/sage/geometry/hyperplane_arrangement/arrangement.py, src/sage/geometry/lattice_polytope.py, src/sage/geometry/polyhedron/base6.py, src/sage/lfunctions/zero_sums.pyx, src/sage/matroids/chow_ring.py, src/sage/matroids/chow_ring_ideal.py, src/sage/matroids/matroid.pyx, src/sage/modular/modform_hecketriangle/abstract_ring.py, src/sage/modular/modform_hecketriangle/graded_ring_element.py, src/sage/modules/filtered_vector_space.py, src/sage/schemes/curves/affine_curve.py, src/sage/schemes/curves/plane_curve_arrangement.py, src/sage/schemes/elliptic_curves/ell_modular_symbols.py, src/sage/schemes/elliptic_curves/ell_rational_field.py, src/sage/schemes/elliptic_curves/heegner.py, src/sage/schemes/hyperelliptic_curves/jacobian_endomorphism_utils.py, src/sage/schemes/hyperelliptic_curves/jacobian_generic.py
- **src/sage/modular/modform_hecketriangle/graded_ring_element.py: Modularization fix for import of HyperbolicPlane**
- **src/sage/modular/modform_hecketriangle/abstract_ring.py: Use lazy_import**
- **src/sage/schemes/curves/plane_curve_arrangement.py: Use lazy_import**
- **src/sage/schemes: Add # needs**
- **src/sage/modules/filtered_vector_space.py: Add # needs**
- **src/sage/categories/filtered_modules_with_basis.py: Add # needs**
- **src/sage/coding/kasami_codes.pyx: Add # needs**
- **src/sage/dynamics/arithmetic_dynamics/projective_ds.py: Add # needs**
- **src/sage/geometry/cone_critical_angles.py: Add # needs**
- **src/sage/geometry/hyperplane_arrangement/arrangement.py: Add # needs**
- **src/sage/geometry/lattice_polytope.py: Do not fail in repr when polytope index cannot be …
=> pkgs/sagemath-schemes: Modularization fixes

src/pyproject.toml
This reverts commit fb1c6bf5c3e069a1380410f12fffc35a9745e4fb.
=> Revert "src/pyproject.toml: Pin cypari2 to a version for which PyPI wheels exist"

pkgs/sagemath-graphs/known-test-failures--modules--pari.json, pkgs/sagemath-graphs/known-test-failures--modules.json, pkgs/sagemath-graphs/known-test-failures.json, src/sage/categories/simplicial_sets.py, src/sage/combinat/permutation.py, src/sage/combinat/shard_order.py, src/sage/doctest/control.py, src/sage/graphs/graph.py, src/sage/graphs/graph_generators.py, src/sage/graphs/matching.py, src/sage/graphs/strongly_regular_db.pyx, src/sage/knots/free_knotinfo_monoid.py, src/sage/misc/classgraph.py, src/sage/misc/rest_index_of_methods.py
- **src/sage/doctest/control.py: Override spkg feature buckygen**
- **src/sage/graphs: Add # needs**
- **src/sage/categories/simplicial_sets.py: Add # needs**
- **src/sage/combinat: Add # needs**
- **src/sage/graphs: Add # needs**
- **src/sage/knots/free_knotinfo_monoid.py: Add # needs**
- **src/sage/misc/classgraph.py: Add # needs**
- **src/sage/misc/rest_index_of_methods.py: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-graphs*' --update-known-test-failures**
=> pkgs/sagemath-graphs: Doctest fixes

pkgs/sagemath-categories/known-test-failures.json, src/sage/misc/sageinspect.py, src/sage/rings/polynomial/multi_polynomial_ideal.py
- **src/sage/rings/polynomial/multi_polynomial_ideal.py: Accept (ignore) keyword 'check'**
- **src/sage/misc/sageinspect.py: Add # needs**
=> sage.rings.polynomial.multi_polynomial_ideal: Modularization fix

pkgs/sagemath-modules/known-test-failures.json, src/sage/functions/gamma.py, src/sage/misc/sage_eval.py, src/sage/stats/distributions/discrete_gaussian_lattice.py
- **src/sage/stats/distributions/discrete_gaussian_lattice.py: Use lazy_import**
- **src/sage/misc/sage_eval.py: Try sage.all__sagemath_modules as toplevel**
- **src/sage/stats/distributions/discrete_gaussian_lattice.py: Add # needs**
- **src/sage/functions/gamma.py: Add # needs**
=> pkgs/sagemath-modules: Modularization fixes

pkgs/sagemath-categories/MANIFEST.in, pkgs/sagemath-categories/known-test-failures.json, pkgs/sagemath-combinat/MANIFEST.in, pkgs/sagemath-flint/known-test-failures.json, pkgs/sagemath-modules/known-test-failures.json, src/sage/combinat/all__sagemath_categories.py, src/sage/combinat/all__sagemath_combinat.py, src/sage/combinat/colored_permutations.py, src/sage/combinat/partition.py, src/sage/combinat/partition_tuple.py, src/sage/combinat/q_analogues.py, src/sage/matrix/misc_flint.pyx, src/sage/modules/finite_submodule_iter.pyx, src/sage/parallel/map_reduce.py, src/sage/rings/lazy_series_ring.py, src/sage/structure/element.pxd, src/sage/structure/element.pyx
- **src/sage/combinat/partition.py: Add # needs**
- **pkgs/sagemath-categories: Move sage.combinat.q_analogues here from sagemath-combinat**
- **src/sage/matrix/misc_flint.pyx: Add # needs**
- **src/sage/modules/finite_submodule_iter.pyx: Add # needs**
- **src/sage/parallel/map_reduce.py: Add # needs**
- **src/sage/structure/element.pyx: Add # needs**
- **src/sage/combinat/partition.py: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-flint' --update-known-test-failures**
- **src/sage/combinat/q_analogues.py: Add # needs**
- **src/sage/combinat/q_analogues.py: Add # needs**
- **src/sage/structure/element.pxd: Remove some # needs sage.combinat**
- **./sage --fixdoctests …
=> pkgs/sagemath-categories: Move sage.combinat.q_analogues here from sagemath-combinat

pkgs/sagemath-flint/known-test-failures.json, src/sage/categories/additive_magmas.py, src/sage/categories/modules_with_basis.py, src/sage/features/sagemath.py, src/sage/graphs/graph.py, src/sage/rings/padics/local_generic_element.pyx, src/sage/rings/padics/padic_generic_element.pyx, src/sage/schemes/hyperelliptic_curves/hypellfrob.pyx, src/sage/schemes/projective/projective_subscheme.py, src/sage/structure/parent.pyx
- **src/sage/structure/parent.pyx: Add # needs**
- **src/sage/schemes: Add # needs**
- **src/sage/rings/padics/padic_generic_element.pyx: Add # needs**
- **src/sage/rings/padics/local_generic_element.pyx: Remove use of predefined x in doctest**
- **src/sage/features/sagemath.py: Fix sage.rings.padics**
- **src/sage/graphs/graph.py: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-flint' --update-known-test-failures**
=> pkgs/sagemath-flint: Fixes

pkgs/sagemath-schemes/known-test-failures--ntl.json, pkgs/sagemath-schemes/known-test-failures--pari.json, pkgs/sagemath-schemes/known-test-failures.json, src/sage/all__sagemath_polyhedra.py, src/sage/arith/misc.py, src/sage/geometry/hyperplane_arrangement/arrangement.py, src/sage/geometry/polyhedron/base6.py, src/sage/libs/singular/function.pyx, src/sage/libs/singular/groebner_strategy.pyx, src/sage/matrix/matrix2.pyx, src/sage/modular/arithgroup/farey_symbol.pyx, src/sage/modular/drinfeld_modform/ring.py, src/sage/modular/hypergeometric_motive.py, src/sage/modular/modform/find_generators.py, src/sage/modular/modform/ring.py, src/sage/modular/overconvergent/hecke_series.py, src/sage/modular/pollack_stevens/fund_domain.py, src/sage/modular/pollack_stevens/manin_map.py, src/sage/modular/pollack_stevens/padic_lseries.py, src/sage/modular/pollack_stevens/space.py, src/sage/modular/quasimodform/element.py, src/sage/modular/quasimodform/ring.py, src/sage/rings/function_field/jacobian_hess.py, src/sage/rings/polynomial/weil/weil_polynomials.pyx, src/sage/rings/qqbar.py, src/sage/rings/valuation/valuation.py, src/sage/schemes/curves/projective_curve.py, src/sage/schemes/elliptic_curves/ell_rational_field.py, src/sage/schemes/elliptic_curves/lseries_ell.py, src/sage/schemes/elliptic_curves/padic_lseries.py
- **src/sage/schemes: Add # needs**
- **src/sage/all__sagemath_polyhedra.py: Override RR import**
- **./sage --fixdoctests --distribution 'sagemath-schemes*' --update-known-test-failures**
- **src/sage/arith/misc.py: Add # needs**
- **src/sage/geometry: Add # needs**
- **src/sage/libs/singular: Add # needs**
- **src/sage/matrix/matrix2.pyx: Add # needs**
- **src/sage/modular: Add # needs**
- **src/sage/schemes/elliptic_curves/ell_rational_field.py: Add # needs**
=> pkgs/sagemath-schemes: Doctest fixes

build/pkgs/boost_cropped/distros/debian.txt
=> build/pkgs/boost_cropped/distros/debian.txt: Add libboost-regex-dev

src/sage/libs/braiding.pyx
=> src/sage/libs/braiding.pyx: Use std=c++11

pkgs/sagemath-flint/MANIFEST.in, pkgs/sagemath-linbox/MANIFEST.in, src/sage/features/sagemath.py, src/sage/libs/linbox/linbox_flint_interface.pxd, src/sage/libs/linbox/linbox_flint_interface.pyx, src/sage/matrix/change_ring.pyx, src/sage/matrix/matrix_cyclo_dense.pyx, src/sage/matrix/matrix_cyclo_linbox.pyx, src/sage/matrix/matrix_integer_dense.pxd, src/sage/matrix/matrix_integer_dense.pyx, src/sage/matrix/matrix_integer_dense_hnf.py, src/sage/matrix/matrix_integer_dense_saturation.py, src/sage/matrix/matrix_integer_iml.pyx, src/sage/matrix/matrix_integer_linbox.pxd, src/sage/matrix/matrix_integer_linbox.pyx, src/sage/matrix/matrix_integer_pari.pyx, src/sage/matrix/matrix_integer_sparse.pyx, src/sage/matrix/matrix_integer_sparse_linbox.pyx, src/sage/matrix/matrix_modn_dense_template.pxi, src/sage/matrix/matrix_rational_dense.pyx, src/sage/matrix/matrix_rational_linbox.pyx, src/sage/matrix/matrix_rational_pari.pyx, src/sage/matrix/matrix_rational_sparse.pyx, src/sage/rings/number_field/S_unit_solver.py, src/sage/rings/number_field/number_field_base.pyx, src/sage/rings/valuation/augmented_valuation.py, src/sage/rings/valuation/valuation.py
Moving these modules to **sagemath-flint** (from **sagemath-linbox**).
Methods depending on Linbox, IML, Pari are split out to separate Cython modules, which are imported at runtime when needed.
=> `sage.matrix.matrix_{integer,rational}_*` modularization 

pkgs/sagemath-symbolics/known-test-failures.json, pkgs/sagemath-symbolics/pyproject.toml.m4, src/sage/calculus/calculus.py, src/sage/functions/orthogonal_polys.py, src/sage/interfaces/mathematica.py, src/sage/interfaces/mathics.py, src/sage/interfaces/maxima.py, src/sage/interfaces/maxima_abstract.py, src/sage/interfaces/sympy_wrapper.py, src/sage/libs/flint/nmod_poly_linkage.pxi, src/sage/manifolds/chart_func.py, src/sage/manifolds/differentiable/manifold.py, src/sage/rings/complex_arb.pyx, src/sage/rings/complex_mpfr.pyx, src/sage/rings/padics/misc.py, src/sage/rings/polynomial/polynomial_rational_flint.pyx, src/sage/rings/polynomial/polynomial_zmod_flint.pyx, src/sage/rings/polynomial/weil/weil_polynomials.pyx, src/sage/rings/real_mpfr.pyx, src/sage/symbolic/constants.py, src/sage/symbolic/expression.pyx, src/sage/symbolic/expression_conversion_algebraic.py, src/sage/symbolic/expression_conversions.py, src/sage/symbolic/pynac_impl.pxi, src/sage/symbolic/relation.py, src/sage/symbolic/ring.pyx
- **pkgs/sagemath-symbolics/pyproject.toml.m4: Remove pari deps**
- **src/sage/calculus/calculus.py: Add # needs**
- **src/sage/functions/orthogonal_polys.py: Add # needs**
- **src/sage/interfaces: Add # needs**
- **src/sage/libs/flint/nmod_poly_linkage.pxi: Fix typo in doctest**
- **src/sage/manifolds: Add # needs**
- **src/sage/rings/complex_mpfr.pyx: Modularize pari import**
- **src/sage/rings/polynomial/polynomial_rational_flint.pyx: Modularize pari import**
- **src/sage/rings/padics/misc.py: Add # needs**
- **src/sage/symbolic: Add # needs**
- **src/sage/symbolic: Add # needs**
- **src/sage/symbolic/relation.py: Add # needs**
- **src/sage/interfaces/sympy_wrapper.py: Add # needs**
- **./sage --fixdoctests …
=> pkgs/sagemath-symbolics: Remove pari dependency

pkgs/sagemath-schemes/MANIFEST.in, pkgs/sagemath-schemes/known-test-failures--ntl.json, pkgs/sagemath-schemes/known-test-failures--pari.json, pkgs/sagemath-schemes/known-test-failures.json, pkgs/sagemath-schemes/pyproject.toml.m4, src/sage/rings/all__sagemath_schemes.py, src/sage/rings/polynomial/all__sagemath_schemes.py, src/sage/rings/polynomial/binary_form_reduce.py, src/sage/rings/polynomial/multi_polynomial_libsingular.pyx, src/sage/schemes/elliptic_curves/ell_finite_field.py, src/sage/schemes/elliptic_curves/ell_rational_field.py, src/sage/schemes/elliptic_curves/heegner.py, src/sage/schemes/elliptic_curves/hom_sum.py, src/sage/schemes/elliptic_curves/padic_lseries.py, src/sage/schemes/elliptic_curves/padics.py
- **src/sage/rings/polynomial/multi_polynomial_libsingular.pyx: Modularize import from cypari2**
- **src/sage/schemes/elliptic_curves: Add # needs**
- **src/sage/rings/polynomial/multi_polynomial_libsingular.pyx: Modularize import from cypari2 (fixup)**
- **src/sage/schemes/elliptic_curves: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-schemes*' --update-known-test-failures**
- **pkgs/sagemath-schemes: Add sage.rings.polynomial.binary_form_reduce**
- **pkgs/sagemath-schemes: Add fpylll, primecountpy as dependencies**
- **./sage --fixdoctests --distribution 'sagemath-schemes*' --update-known-test-failures**
- **src/sage/schemes/elliptic_curves/heegner.py: Add # needs**
=> pkgs/sagemath-schemes: Add dependencies, fix doctests

pkgs/sagemath-cddlib/known-test-failures.json, pkgs/sagemath-cddlib/pyproject.toml.m4, pkgs/sagemath-gap/pyproject.toml.m4, pkgs/sagemath-groups/known-test-failures.json, pkgs/sagemath-groups/pyproject.toml.m4, pkgs/sagemath-latte-4ti2/pyproject.toml.m4, pkgs/sagemath-lrslib/pyproject.toml.m4, pkgs/sagemath-msolve/pyproject.toml.m4, pkgs/sagemath-palp/known-test-failures.json, pkgs/sagemath-palp/pyproject.toml.m4, pkgs/sagemath-topcom/pyproject.toml.m4, src/sage/all__sagemath_polyhedra.py, src/sage/geometry/hyperplane_arrangement/arrangement.py, src/sage/geometry/lattice_polytope.py, src/sage/geometry/polyhedron/base5.py, src/sage/geometry/polyhedron/base6.py, src/sage/geometry/polyhedron/base_mutable.py, src/sage/geometry/polyhedron/library.py, src/sage/geometry/polyhedron/ppl_lattice_polygon.py, src/sage/geometry/polyhedron/ppl_lattice_polytope.py, src/sage/geometry/triangulation/element.py
- **pkgs/sagemath-{cddlib,groups,latte-4ti2,msolve,palp,topcom}: Replace sagemath-linbox by sagemath-flint in runtime deps**
- **pkgs/sagemath-gap: Restore sage-conf runtime dep**
- **./sage --fixdoctests --distribution 'sagemath-groups' --update-known-test-failures**
- **pkgs/sagemath-cddlib/pyproject.toml.m4: Test with sagemath-pari**
- **src/sage/geometry/lattice_polytope.py: Catch FeatureNotPresentError when looking up polytope index**
- **src/sage/geometry/polyhedron: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-cddlib' --update-known-test-failures**
- **pkgs/sagemath-palp/pyproject.toml.m4: Test with sagemath-pari**
- **src/sage/geometry: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-palp' --update-known-test-failures**
- …
=> pkgs/sagemath-{cddlib,groups,latte-4ti2,msolve,palp,topcom}: Remove linbox dependency

pkgs/sagemath-maxima/pyproject.toml.m4, pkgs/sagemath-symbolics/known-test-failures.json, src/sage/algebras/clifford_algebra.py, src/sage/calculus/calculus.py, src/sage/categories/chain_complexes.py, src/sage/geometry/toric_lattice.py, src/sage/groups/additive_abelian/additive_abelian_group.py, src/sage/groups/additive_abelian/additive_abelian_wrapper.py, src/sage/homology/chain_complex.py, src/sage/homology/matrix_utils.py, src/sage/interfaces/magma.py, src/sage/manifolds/differentiable/manifold.py, src/sage/matrix/matrix2.pyx, src/sage/matrix/matrix_integer_dense.pyx, src/sage/matrix/matrix_integer_dense_hnf.py, src/sage/matrix/matrix_rational_dense.pyx, src/sage/matrix/symplectic_basis.py, src/sage/matroids/database_matroids.py, src/sage/matroids/linear_matroid.pyx, src/sage/matroids/matroid.pyx, src/sage/quadratic_forms/binary_qf.py, src/sage/quadratic_forms/quadratic_form__split_local_covering.py, src/sage/quadratic_forms/quadratic_form__ternary_Tornaria.py, src/sage/quadratic_forms/ternary_qf.py, src/sage/rings/number_field/order_ideal.py, src/sage/rings/polynomial/complex_roots.py, src/sage/rings/polynomial/polynomial_element.pyx, src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx, src/sage/stats/distributions/discrete_gaussian_lattice.py, src/sage/symbolic/expression.pyx
- **pkgs/sagemath-maxima: Add sage-conf, sagemath-environment dependencies**
- **src/sage/quadratic_forms/binary_qf.py: Fall back to 'sage' when pari is not available**
- **src/sage/interfaces/magma.py: Add # needs**
- **src/sage/homology/matrix_utils.py: Add # needs**
- **src/sage/manifolds/differentiable/manifold.py: Add # needs**
- **src/sage/matrix: Add # needs**
- **src/sage/matroids: Add # needs**
- **src/sage/symbolic/expression.pyx: Add # needs**
- **src/sage/stats/distributions/discrete_gaussian_lattice.py: Add # needs**
- **src/sage/quadratic_forms: Add # needs**
- **src/sage/algebras/clifford_algebra.py: Add # needs**
- **src/sage/calculus/calculus.py: Add # needs**
- **src/sage/categories/chain_complexes.py: Add # needs**
- **src/sage/matrix: …
=> pkgs/sagemath-symbolics: Make sure maxima is found, fix doctests

build/pkgs/gap/spkg-install.in
- Workaround for https://github.com/gap-system/gap/issues/5882
=> build/pkgs/gap/spkg-install.in: Use 'make -j1 install'

pkgs/sagemath-linbox/known-test-failures.json, pkgs/sagemath-linbox/pyproject.toml.m4, src/sage/arith/multi_modular.pyx
- **pkgs/sagemath-linbox/pyproject.toml.m4: Define extra 'primecountpy'**
- **src/sage/arith/multi_modular.pyx: Make use of prime_count optional**
- **./sage --fixdoctests --distribution 'sagemath-linbox' --update-known-test-failures**
=> sage.arith.multi_modular: Make use of prime_count optional

build/pkgs/cmr/spkg-install.in
=> build/pkgs/cmr: Set rpath when linking test executables

build/pkgs/_prereq/distros/fedora.txt
`awk` is missing in the fedora-42 Docker images.
https://github.com/passagemath/passagemath/actions/runs/14580835120/job/40896989229#step:11:3122
=> fedora: Add gawk to minimal requirements

pkgs/sagemath-repl/pyproject.toml.m4
This fixes the following:
```
[sagemath_categories-10.5.25] [spkg-check] Traceback (most recent call last):
[sagemath_categories-10.5.25] [spkg-check]   File "/sage/pkgs/sagemath-categories/.tox/sagepython-sagewheels-nopypi-norequirements/lib/python3.10/site-packages/sage/repl/rich_output/display_manager.py", line 41, in <module>
[sagemath_categories-10.5.25] [spkg-check]     from typing import Self  # type: ignore (Python >= 3.11)
[sagemath_categories-10.5.25] [spkg-check] ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)
[sagemath_categories-10.5.25] [spkg-check] 
[sagemath_categories-10.5.25] [spkg-check] During handling of the above exception, another exception occurred:
[sagemath_categories-10.5.25] [spkg-check] 
[sagemath_categories-10.5.25] …
```
=> pkgs/sagemath-repl: Require typing_extensions (on older Python)

.homebrew-build-env, build/pkgs/patch/spkg-configure.m4
regex fix in `spkg-configure.m4`
- Fixes https://github.com/sagemath/sage/issues/39941
This alone does not suffice to make current homebrew's `gpatch` to be recognized:
Since October 2024 (https://github.com/Homebrew/homebrew-core/commits/229400baf382d26981998bbe78dd490caa97830b/Formula/g/gpatch.rb), the `gpatch` packages no longer installs a `patch` binary in the normal PATH, only `gpatch`.
Here we also update `.homebrew-build-env` to supply `/usr/local/opt/gpatch/libexec/gnubin`, where the `patch` binary is installed.
=> build/pkgs/patch: Recognize 2-part version numbers, find homebrew patch

tox.ini
Until GCC 15 is supported by the Sage distribution.
=> tox.ini: Allow use of GCC spkg on archlinux, fedora-42

build/pkgs/numpy/patches/27416.patch
- Add https://github.com/numpy/numpy/pull/27416 as a patch
- Fixes #719
=> build/pkgs/numpy: Fix build on macOS with clang 17

build/pkgs/m4ri/spkg-configure.m4
=> build/pkgs/m4ri/spkg-configure.m4: Reject m4ri when m4ri.pc is broken as on current Debian

build/pkgs/lidia/spkg-install.in
Backport of:
- https://github.com/sagemath/sage/pull/39919
=> lidia: support modern compilers that default to C++17 by @isuruf, backported

.github/workflows/ci-wheels.yml, README.md
Since https://github.com/passagemath/passagemath/releases/tag/passagemath-10.5.32, Linux ARM wheels are available @xuluze but some 3rd party packages have not published wheels for this platform.
Here we document a robust procedure for building these wheels on the user's system.
=> README.md: Procedure for building missing wheels of 3rd party packages (Linux ARM, Python 3.13, ...)

pkgs/sage-conf_pypi/setup.py
This fixes a parallelization bug
=> pkgs/sage-conf_pypi/setup.py: Do not pass -j to top-level make

.github/workflows/build.yml, .github/workflows/ci-conda.yml, .github/workflows/doc-build-pdf.yml, .github/workflows/doc-build.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/macos.yml
Disable the "CI Fixes" mechanism, which is not useful at the moment.
If re-enabled, should work on this for more robustness:
- #807
=> Ci fixes disable

.github/workflows/dist.yml
Failing persistenly with
```
Run softprops/action-gh-release@v2
⚠️ Unexpected error fetching GitHub release for tag refs/tags/passagemath-10.5.34: HttpError: We couldn't respond to your request in time. Sorry about that. Please try resubmitting your request and contact us if the problem persists.
Error: We couldn't respond to your request in time. Sorry about that. Please try resubmitting your request and contact us if the problem persists.
```
=> .github/workflows/dist.yml: Replace use of softprops/action-gh-release

src/sage/matrix/matrix2.pyx, src/sage/matrix/matrix_cmr_sparse.pyx, src/sage/matrix/matrix_integer_dense.pyx, src/sage/matrix/matrix_sparse.pyx
Also fixes the crash when calling `matrix_from_rows_and_columns` @xuluze @discopt
=> `sage.matrix.matrix2`: Add methods `is_unimodular`... delegating to `Matrix_cmr_sparse`

.github/workflows/dist.yml
=> .github/workflows/dist.yml: Use 'secrets: inherit' when invoking pypi-publish.yml

src/sage/matrix/matrix_cmr_sparse.pyx
Some markup fixes, trying to get the doc to compile @xuluze
=> src/sage/matrix/matrix_cmr_sparse.pyx: Fix sphinx markup in docstrings

pkgs/sagemath-singular/known-test-failures.json, src/sage/algebras/all.py, src/sage/algebras/all__sagemath_singular.py, src/sage/algebras/quatalg/quaternion_algebra.py
- **src/sage/algebras/quatalg/quaternion_algebra.py: Use lazy_import**
- **src/sage/algebras/all__sagemath_singular.py: Add sage.algebras.quatalg**
- **src/sage/algebras/quatalg/quaternion_algebra.py: Add # needs**
- **./sage --fixdoctests --distribution 'sagemath-singular' --update-known-test-failures**
=> sage.algebras.quatalg modularization

pkgs/sagemath-categories/known-test-failures.json, pkgs/sagemath-repl/known-test-failures.json, pkgs/sagemath-repl/setup.py
- **pkgs/sagemath-repl/setup.py: Add sage/ext_data/notebook-ipython to package data**
- **./sage --fixdoctests --distribution 'sagemath-repl' --update-known-test-failures**
=> passagemath-repl: Ship sage.ext_data.notebook-ipython as package data

src/sage/all.py, src/sage/misc/lazy_import.pyx
=> src/sage/misc/lazy_import.pyx: Show startup warnings only when sage.all is loaded

pkgs/sagemath-combinat/known-test-failures--graphs.json, pkgs/sagemath-combinat/known-test-failures--modules.json, pkgs/sagemath-combinat/known-test-failures.json, src/sage/combinat/designs/incidence_structures.py, src/sage/combinat/permutation.py, src/sage/combinat/plane_partition.py, src/sage/combinat/posets/linear_extension_iterator.pyx, src/sage/combinat/posets/linear_extensions.py, src/sage/combinat/ribbon_shaped_tableau.py, src/sage/combinat/skew_tableau.py, src/sage/combinat/tableau.py, src/sage/combinat/tableau_tuple.py, src/sage/graphs/generators/distance_regular.pyx, src/sage/graphs/graph.py, src/sage/matrix/special.py, src/sage/misc/latex.py
- **src/sage/combinat/designs/incidence_structures.py: Add # needs**
- **src/sage/combinat/posets/linear_extension_iterator.pyx: Explicitly import sage.matrix**
- **src/sage/combinat: Mark various poset-related doctests # needs sage.modules**
- **Various # needs**
- **./sage --fixdoctests --distribution 'sagemath-combinat[*]' --update-known-test-failures**
=> sage.combinat: Mark various poset-related doctests # needs sage.modules

constraints_pkgs.txt
I also need to `pip install jinja2` in the virtual environment to install `passagemath-standard` successfully for dependance of `passagemath-modules` and `passagemath-catagories`.
=> fix a typo from sagemath-eclib to sagemath-ecl in constraints_pkgs.txt

src/doc/en/developer/coding_in_python.rst
- sagemath/sage#35203 added these packages as unconditional dependencies
- prompted by a sporadic use of typing_extensions in the Sage library (see sagemath/sage#34831)
- motivated further by the demand to immediately drop support for Python 3.8 so that newer typing features can be used in the Sage library (https://github.com/sagemath/sage/pull/35404)
- https://github.com/sagemath/sage/pull/36776 reduced the packages to conditional dependencies
Here we improve the documentation in the section "Language standard" of the developer's guide so that it aligns with how the conditional dependencies are declared.
Rebased from:
- https://github.com/sagemath/sage/pull/37654
=> Developer guide: Improve discussion of backport packages

build/pkgs/_prereq/distros/arch.txt
```
[macaulay2-git]   [spkg-install] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:227 (message):
[macaulay2-git]   [spkg-install]   Could NOT find BISON (missing: BISON_EXECUTABLE)
```
https://github.com/passagemath/M2/actions/runs/15029437670/job/42822578109#step:11:6056
=> build/pkgs/_prereq/distros/arch.txt: Add bison (for macaulay2)

build/pkgs/normaliz/spkg-install.in
Workaround for:
- https://github.com/Macaulay2/M2/issues/3849
=> build/pkgs/normaliz: Disable use of cocoalib as a workaround for M2

build/pkgs/cmake/spkg-configure.m4
This affected the M2 build using cibuildwheel v2.23.3, which supplies this version.
- https://github.com/Macaulay2/M2/issues/3855
=> build/pkgs/cmake/spkg-configure.m4: Reject broken cmake 4.0.0

build/pkgs/py4ti2/checksums.ini, build/pkgs/py4ti2/package-version.txt
https://pypi.org/project/Py4ti2/ is now up, thanks @alfsan
=> build/pkgs/py4ti2: Switch to release on PyPI

src/sage/databases/sql_db.py, src/sage/functions/transcendental.py, src/sage/geometry/cone_critical_angles.py, src/sage/graphs/graph_list.py, src/sage/modular/hecke/morphism.py, src/sage/plot/animate.py, src/sage/rings/complex_mpfr.pyx, src/sage/rings/number_field/number_field_ideal.py, src/sage/rings/number_field/totallyreal_phc.py, src/sage/rings/polynomial/polynomial_element.pyx, src/sage/rings/power_series_ring_element.pyx, src/sage/rings/qqbar.py, src/sage/sandpiles/sandpile.py, src/sage/schemes/elliptic_curves/formal_group.py, src/sage/schemes/elliptic_curves/padics.py, src/sage/schemes/generic/algebraic_scheme.py, src/sage/schemes/hyperelliptic_curves/monsky_washnitzer.py
`sage.misc.misc` pulls in `sage.env`, thus a dependency on **passagemath-environment**.
=> Replace module-level imports from sage.misc.misc

build/pkgs/python3/spkg-configure.m4
Creates too much friction in particular when used inside passagemath-conf, for unknown benefit (does there really still exist a system Python that we accept but brings incompatible `bzip2` `liblzma` `libffi` `zlib`?)
- Resolves #1013
=> build/pkgs/python3/spkg-configure.m4: Disable DEPCHECK

.upstream.d/15-github.com-passagemath-passagemath-releases, tools/update-version
=> update-version: Use prerelease versions correctly in `.upstream.d`

Makefile
- **Makefile: Remove some unhelpful CONFIGURE_DEPENDENCIES**
- **Makefile (configure): Indicate what triggered the 'bootstrap' run**
=> Reduce CONFIGURE_DEPENDENCIES

Makefile, configure.ac
- **configure.ac: Allow building on mingw**
- **configure.ac [mingw]: Disable file permissions test**
- **Makefile (reconfigure): Create logs/pkgs/config.log before symlinking to it (for mingw)**
=> Allow running configure && make on mingw

src/sage_setup/__init__.py
- **src/sage_setup/__init__.py: Use platform.system instead of os.uname (for mingw)**
- **src/sage_setup/__init__.py: Use platform.system instead of os.uname (for mingw), fixup**
=> src/sage_setup: Use platform.system instead of os.uname (for mingw)

src/sage/doctest/control.py
- **src/sage/doctest/control.py: Set serial in DocTestController.__init__**
- **src/sage/doctest/control.py: Ensure DOT_SAGE exists in DocTestController.__init__**
=> sage.doctest: Properly set 'serial' on Windows, properly ensure DOT_SAGE exists

.github/workflows/dist-wheels-windows.yml, build/pkgs/boost_cropped/spkg-install.in, build/pkgs/zlib/spkg-install.in, src/sage/all__sagemath_bliss.py, src/sage/all__sagemath_coxeter3.py, src/sage/all__sagemath_glpk.py, src/sage/all__sagemath_lcalc.py, src/sage/all__sagemath_libecm.py, src/sage/all__sagemath_linbox.py, src/sage/all__sagemath_mcqd.py, src/sage/all__sagemath_meataxe.py, src/sage/all__sagemath_tdlib.py
- **.github/workflows/dist-wheels-windows.yml: Use GITHUB_WORKSPACE in constraints**
- **src/sage/all__*.py: Add missing '# delvewheel: patch' directives**
- **.github/workflows/dist-wheels-windows.yml: Compute SAGE_LOCAL cache hash key before bootstrapping**
- **build/pkgs/zlib/spkg-install.in: Build and install with -j1**
- **build/pkgs/boost_cropped/spkg-install.in: Disable static libs**
- **build/pkgs/boost_cropped: Disable cobalt**
=> Fixes for Windows wheel build

pkgs/sagemath-latte-4ti2/repair_wheel.py
Report:
Following the example at [pypi.org/project/passagemath-polyhedra/](http://pypi.org/project/passagemath-polyhedra/), I defined P = polytopes.cube() and ran P.integral_points_count(). That worked fine. I then successively ran 
(2*P).integral_points_count(), 
(3*P).integral_points_count(), and 
(4*P).integral_points_count(), 
and those all worked fine.
However, when I ran (5*P).integral_points_count(), I got an error: "[/Users/tmcal/passagemath-venv/lib/python3.9/site-packages/sage_wheels/bin/count](https://file+.vscode-resource.vscode-cdn.net/Users/tmcal/passagemath-venv/lib/python3.9/site-packages/sage_wheels/bin/count):
could not execute [/Users/tmcal/passagemath-venv/lib/python3.9/site-packages/sage_wheels/bin/count.bin](https://file+.vscode-resource.vscode-cdn.net/Users/tmcal/pas …
=> pkgs/sagemath-latte-4ti2: Fix for relocatable LattE/4ti2 binaries

pkgs/sagemath-latte-4ti2/repair_wheel.py
After #1246, we see on musllinux
```
Running set -o pipefail; (cd /host/sage-musllinux_1_2_aarch64 && tar cf - --dereference bin/{ConvertCDDextToLatte,ConvertCDDineToLatte,count,count-linear-forms-from-polynomial,ehrhart,ehrhart3,hilbert-from-rays,hilbert-from-rays-symm,integrate,latte-maximize,latte-minimize,latte2ext,latte2ine,polyhedron-to-cones,top-ehrhart-knapsack,triangulate}* share/latte-int/{m-knapsack.mpl,simplify*.add} bin/{4ti2gmp,4ti2int32,4ti2int64,circuits,genmodel,gensymm,graver,groebner,hilbert,markov,minimize,normalform,output,ppi,qsolve,rays,walk,zbasis,zsolve}*) | (mkdir -p sage_wheels && cd sage_wheels && tar xvf -)
tar: bin/ConvertCDDextToLatte*: Cannot stat: No such file or directory
tar: bin/ConvertCDDineToLatte*: Cannot stat: No such file or directory
bin/countg …
```
=> pkgs/sagemath-latte-4ti2: Fix for relocatable LattE/4ti2 binaries (fixup)

src/pyproject.toml
=> src/pyproject.toml [Windows]: Use cysignals < 1.12.4

src/sage/categories/finite_dimensional_modules_with_basis.py, src/sage/matrix/matrix2.pyx, src/sage/matrix/matrix_cmr_sparse.pyx
The removal can be reverted whenever we wish to implement these methods.
=> Remove unimplemented is_complement_totally_unimodular methods

src/sage/matrix/matrix_cmr_sparse.pyx, src/sage/matrix/seymour_decomposition.pyx
This makes the API more consistent with itself and with the existing matrix API.
It also fixes the problematic grammar in `first_columns_index` (which should have been `first_column_indices` but is now simply `first_column`).
=> CMR: Simplify parameter names (omit `_index`), rename `child_indices` to `child_keys`

pkgs/sagemath-modules/known-test-failures.json, src/sage/categories/finite_dimensional_modules_with_basis.py, src/sage/matrix/matrix_cmr_sparse.pyx
The use of `lazy_attribute` was causing pickling errors in unrelated classes
=> Remove use of `lazy_attribute` for CMR methods for f.d. module morphisms, fix `is_conetwork_matrix` with col/row keys

src/bin/sage, src/bin/sage-env, src/bin/sage-venv-config, src/sage/interfaces/gap.py
... which already handles the GAP_ROOT_PATH correctly.
Revert #1415, which did not work as intended.
=> `sage -gap`: Go through `sage.interfaces.gap.gap_cmd`

pkgs/sagemath-graphs/known-test-failures--modules--pari.json, pkgs/sagemath-graphs/known-test-failures--modules.json, pkgs/sagemath-graphs/known-test-failures.json, pkgs/sagemath-modules/known-test-failures.json, pkgs/sagemath-plot/known-test-failures.json, src/sage/matrix/matrix2.pyx, src/sage/misc/latex.py
When we don't use the specialized matrix implementation for integers, the computed Smith form is not necessarily normalized in the way expected by code using the elementary divisors.
We fix it using the new `canonical_associate` methods.
=> Elementary divisors: Use `canonical_associate`

tox.ini
seen in Normaliz CI
```
Error: cmake was installed from the local/pinned tap
but you are trying to install it from the homebrew/core tap.
Formulae with the same name from different taps cannot be installed at the same time.
To install this version, you must first uninstall the existing formula:
brew uninstall cmake
Then you can install the desired version:
brew install cmake
Warning: Treating cmake as a cask. For the formula, use local/pinned/cmake or specify the `--formula` flag. To silence this message, use the `--cask` flag.
```
https://github.com/passagemath/upstream-Normaliz/actions/runs/17504619687/job/49725453391#step:10:65
@w-bruns
=> tox.ini (homebrew): Work around preinstalled "cmake", formula/cask confusion on GH Actions

README.md
Coinciding with end of security support for Python 3.9 per https://endoflife.date/python
=> README.md: Set EOL for passagemath-10.5.x as 2025-10-31

.github/workflows/dist.yml
Currently, we always have to run the PyPI upload several times after deleting old versions to make room for new ones.
We defer the upload of sdists to this manual step so that the time window with latest versions having no wheels is greatly reduced.
=> .github/workflows/dist.yml: Do not upload sdists to PyPI

pkgs/sagemath-gap/tox.ini
The failure in `wpe` does not show an "Error" annotation in GH Actions
```
testing: 
Error, Cannot read file 
```
https://github.com/passagemath/passagemath/actions/runs/17886625369/job/50874985630#step:9:35495
=> pkgs/sagemath-gap/tox.ini: Make sure ::error:: works in all situations
